// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration
// Assembly: Microsoft.Extensions.Configuration, Microsoft.Extensions.Configuration.Abstractions, Microsoft.Extensions.Configuration.Binder, Microsoft.Extensions.Configuration.CommandLine, Microsoft.Extensions.Configuration.EnvironmentVariables, Microsoft.Extensions.Configuration.FileExtensions, Microsoft.Extensions.Configuration.Ini, Microsoft.Extensions.Configuration.Json, Microsoft.Extensions.Configuration.KeyPerFile, Microsoft.Extensions.Configuration.UserSecrets, Microsoft.Extensions.Configuration.Xml

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { CommandLineConfigurationSource } from "../../Microsoft.Extensions.Configuration.CommandLine/internal/index.js";
import type { EnvironmentVariablesConfigurationSource } from "../../Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js";
import type { IniConfigurationSource } from "../../Microsoft.Extensions.Configuration.Ini/internal/index.js";
import type { JsonConfigurationSource } from "../../Microsoft.Extensions.Configuration.Json/internal/index.js";
import type { KeyPerFileConfigurationSource } from "../../Microsoft.Extensions.Configuration.KeyPerFile/internal/index.js";
import type { XmlConfigurationSource } from "../../Microsoft.Extensions.Configuration.Xml/internal/index.js";
import type { IFileProvider } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import * as Microsoft_Extensions_Primitives_Internal from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IComparer_1, IDictionary_2, IEnumerable_1, IList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { Assembly } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Attribute, Boolean as ClrBoolean, Exception, Func_2, IDisposable, Int32, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IConfiguration$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfiguration: never;

    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export type IConfiguration = IConfiguration$instance & { [key: string]: string | null; };

export interface IConfigurationBuilder$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationBuilder: never;

    readonly Properties: IDictionary_2<System_Internal.String, JsValue>;
    readonly Sources: IList_1<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
}


export type IConfigurationBuilder = IConfigurationBuilder$instance;

export interface IConfigurationManager$instance extends IConfiguration, IConfigurationBuilder {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationManager: never;

    readonly Properties: IDictionary_2<System_Internal.String, JsValue>;
    readonly Sources: IList_1<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export interface IConfigurationManager$instance extends IConfiguration$instance, IConfigurationBuilder$instance {}

export type IConfigurationManager = IConfigurationManager$instance & { [key: string]: string | null; };

export interface IConfigurationProvider$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;

    GetChildKeys(earlierKeys: IEnumerable_1<System_Internal.String>, parentPath: string | null): IEnumerable_1<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string | null): void;
    TryGet(key: string, value: string | null): boolean;
}


export type IConfigurationProvider = IConfigurationProvider$instance;

export interface IConfigurationRoot$instance extends IConfiguration {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationRoot: never;

    readonly Providers: IEnumerable_1<IConfigurationProvider>;
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    Reload(): void;
}


export interface IConfigurationRoot$instance extends IConfiguration$instance {}

export type IConfigurationRoot = IConfigurationRoot$instance & { [key: string]: string | null; };

export interface IConfigurationSection$instance extends IConfiguration {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSection: never;

    readonly Key: string;
    readonly Path: string;
    get Value(): string | null;
    set Value(value: string | null);
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export interface IConfigurationSection$instance extends IConfiguration$instance {}

export type IConfigurationSection = IConfigurationSection$instance & { [key: string]: string | null; };

export interface IConfigurationSource$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export type IConfigurationSource = IConfigurationSource$instance;

export interface ConfigurationDebugViewContext$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationDebugViewContext: never;

    readonly ConfigurationProvider: IConfigurationProvider;
    readonly Key: string;
    readonly Path: string;
    readonly Value: string | null;
}


export const ConfigurationDebugViewContext: {
    new(path: string, key: string, value: string | null, configurationProvider: IConfigurationProvider): ConfigurationDebugViewContext;
};


export type ConfigurationDebugViewContext = ConfigurationDebugViewContext$instance;

export interface BinderOptions$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_BinderOptions: never;

    BindNonPublicProperties: boolean;
    ErrorOnUnknownConfiguration: boolean;
}


export const BinderOptions: {
    new(): BinderOptions;
};


export type BinderOptions = BinderOptions$instance;

export interface ChainedConfigurationProvider$instance extends IConfigurationProvider$instance, System_Internal.IDisposable {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ChainedConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Configuration: IConfiguration;
    Dispose(): void;
    GetChildKeys(earlierKeys: IEnumerable_1<System_Internal.String>, parentPath: string | null): IEnumerable_1<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string | null): void;
    TryGet(key: string, value: string | null): boolean;
}


export const ChainedConfigurationProvider: {
    new(source: ChainedConfigurationSource): ChainedConfigurationProvider;
};


export interface __ChainedConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type ChainedConfigurationProvider = ChainedConfigurationProvider$instance & __ChainedConfigurationProvider$views;


export interface ChainedConfigurationSource$instance extends IConfigurationSource$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ChainedConfigurationSource: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    get Configuration(): IConfiguration | null;
    set Configuration(value: IConfiguration | null);
    ShouldDisposeConfiguration: boolean;
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const ChainedConfigurationSource: {
    new(): ChainedConfigurationSource;
};


export interface __ChainedConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export type ChainedConfigurationSource = ChainedConfigurationSource$instance & __ChainedConfigurationSource$views;


export interface ConfigurationBuilder$instance extends IConfigurationBuilder$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationBuilder: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationBuilder: never;

    readonly Properties: IDictionary_2<System_Internal.String, JsValue>;
    readonly Sources: IList_1<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
}


export const ConfigurationBuilder: {
    new(): ConfigurationBuilder;
};


export interface __ConfigurationBuilder$views {
    As_IConfigurationBuilder(): IConfigurationBuilder$instance;
}

export type ConfigurationBuilder = ConfigurationBuilder$instance & __ConfigurationBuilder$views;


export interface ConfigurationKeyComparer$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationKeyComparer: never;

    readonly __tsonic_iface_System_Collections_Generic_IComparer_1: never;

    Compare(x: string | null, y: string | null): int;
}


export const ConfigurationKeyComparer: {
    new(): ConfigurationKeyComparer;
    readonly Instance: ConfigurationKeyComparer;
};


export type ConfigurationKeyComparer = ConfigurationKeyComparer$instance;

export interface ConfigurationKeyNameAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationKeyNameAttribute: never;

    readonly Name: string;
}


export const ConfigurationKeyNameAttribute: {
    new(name: string): ConfigurationKeyNameAttribute;
};


export type ConfigurationKeyNameAttribute = ConfigurationKeyNameAttribute$instance;

export interface ConfigurationManager$instance extends System_Internal.IDisposable {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationManager: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfiguration: never;
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationBuilder: never;
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationManager: never;
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationRoot: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Sources: IList_1<IConfigurationSource>;
    Dispose(): void;
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetSection(key: string): IConfigurationSection;
}


export const ConfigurationManager: {
    new(): ConfigurationManager;
};


export interface __ConfigurationManager$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationBuilder(): IConfigurationBuilder$instance;
    As_IConfigurationRoot(): IConfigurationRoot$instance;
}

export type ConfigurationManager = ConfigurationManager$instance & __ConfigurationManager$views & { [key: string]: string | null; };


export interface ConfigurationProvider$instance extends IConfigurationProvider$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;

    GetChildKeys(earlierKeys: IEnumerable_1<System_Internal.String>, parentPath: string | null): IEnumerable_1<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string | null): void;
    ToString(): string;
    TryGet(key: string, value: string | null): boolean;
}


export const ConfigurationProvider: (abstract new() => ConfigurationProvider) & {
};


export interface __ConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type ConfigurationProvider = ConfigurationProvider$instance & __ConfigurationProvider$views;


export interface ConfigurationReloadToken$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationReloadToken: never;

    readonly __tsonic_iface_Microsoft_Extensions_Primitives_IChangeToken: never;

    ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
    OnReload(): void;
    RegisterChangeCallback(callback: Action_1<JsValue | null>, state: JsValue | null): IDisposable;
}


export const ConfigurationReloadToken: {
    new(): ConfigurationReloadToken;
};


export interface __ConfigurationReloadToken$views {
    As_IChangeToken(): Microsoft_Extensions_Primitives_Internal.IChangeToken$instance;
}

export type ConfigurationReloadToken = ConfigurationReloadToken$instance & __ConfigurationReloadToken$views;


export interface ConfigurationRoot$instance extends System_Internal.IDisposable {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationRoot: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfiguration: never;
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationRoot: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Providers: IEnumerable_1<IConfigurationProvider>;
    Dispose(): void;
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    Reload(): void;
}


export const ConfigurationRoot: {
    new(providers: IList_1<IConfigurationProvider>): ConfigurationRoot;
};


export interface __ConfigurationRoot$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationRoot(): IConfigurationRoot$instance;
}

export type ConfigurationRoot = ConfigurationRoot$instance & __ConfigurationRoot$views & { [key: string]: string | null; };


export interface ConfigurationSection$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_ConfigurationSection: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfiguration: never;
    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSection: never;

    readonly Key: string;
    readonly Path: string;
    get Value(): string | null;
    set Value(value: string | null);
    GetChildren(): IEnumerable_1<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    TryGetValue(key: string | null, value: string | null): boolean;
}


export const ConfigurationSection: {
    new(root: IConfigurationRoot, path: string): ConfigurationSection;
};


export interface __ConfigurationSection$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationSection(): IConfigurationSection$instance;
}

export type ConfigurationSection = ConfigurationSection$instance & __ConfigurationSection$views & { [key: string]: string | null; };


export interface FileConfigurationProvider$instance extends ConfigurationProvider$instance, System_Internal.IDisposable {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_FileConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Source: FileConfigurationSource;
    Dispose(): void;
    Dispose(disposing: boolean): void;
    Load(): void;
    Load(stream: Stream): void;
    ToString(): string;
}


export const FileConfigurationProvider: (abstract new(source: FileConfigurationSource) => FileConfigurationProvider) & {
};


export interface __FileConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type FileConfigurationProvider = FileConfigurationProvider$instance & __FileConfigurationProvider$views;


export interface FileConfigurationSource$instance extends IConfigurationSource$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_FileConfigurationSource: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    get FileProvider(): IFileProvider | null;
    set FileProvider(value: IFileProvider | null);
    get OnLoadException(): Action_1<FileLoadExceptionContext> | null;
    set OnLoadException(value: Action_1<FileLoadExceptionContext> | null);
    Optional: boolean;
    get Path(): string | null;
    set Path(value: string | null);
    ReloadDelay: int;
    ReloadOnChange: boolean;
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
    EnsureDefaults(builder: IConfigurationBuilder): void;
    ResolveFileProvider(): void;
}


export const FileConfigurationSource: (abstract new() => FileConfigurationSource) & {
};


export interface __FileConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export type FileConfigurationSource = FileConfigurationSource$instance & __FileConfigurationSource$views;


export interface FileLoadExceptionContext$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_FileLoadExceptionContext: never;

    Exception: Exception;
    Ignore: boolean;
    Provider: FileConfigurationProvider;
}


export const FileLoadExceptionContext: {
    new(): FileLoadExceptionContext;
};


export type FileLoadExceptionContext = FileLoadExceptionContext$instance;

export interface StreamConfigurationProvider$instance extends ConfigurationProvider$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_StreamConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;

    readonly Source: StreamConfigurationSource;
    Load(stream: Stream): void;
    Load(): void;
}


export const StreamConfigurationProvider: (abstract new(source: StreamConfigurationSource) => StreamConfigurationProvider) & {
};


export interface __StreamConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type StreamConfigurationProvider = StreamConfigurationProvider$instance & __StreamConfigurationProvider$views;


export interface StreamConfigurationSource$instance extends IConfigurationSource$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_StreamConfigurationSource: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    get Stream(): Stream | null;
    set Stream(value: Stream | null);
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const StreamConfigurationSource: (abstract new() => StreamConfigurationSource) & {
};


export interface __StreamConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export type StreamConfigurationSource = StreamConfigurationSource$instance & __StreamConfigurationSource$views;


export abstract class ChainedBuilderExtensions$instance {
    static AddConfiguration(configurationBuilder: IConfigurationBuilder, config: IConfiguration, shouldDisposeConfiguration: boolean): IConfigurationBuilder;
    static AddConfiguration(configurationBuilder: IConfigurationBuilder, config: IConfiguration): IConfigurationBuilder;
}


export type ChainedBuilderExtensions = ChainedBuilderExtensions$instance;

export abstract class CommandLineConfigurationExtensions$instance {
    static AddCommandLine(builder: IConfigurationBuilder, configureSource: Action_1<CommandLineConfigurationSource> | null): IConfigurationBuilder;
    static AddCommandLine(configurationBuilder: IConfigurationBuilder, args: string[], switchMappings: IDictionary_2<System_Internal.String, System_Internal.String> | null): IConfigurationBuilder;
    static AddCommandLine(configurationBuilder: IConfigurationBuilder, args: string[]): IConfigurationBuilder;
}


export type CommandLineConfigurationExtensions = CommandLineConfigurationExtensions$instance;

export abstract class ConfigurationBinder$instance {
    static Bind(configuration: IConfiguration, instance: JsValue | null, configureOptions: Action_1<BinderOptions> | null): void;
    static Bind(configuration: IConfiguration, instance: JsValue | null): void;
    static Bind(configuration: IConfiguration, key: string, instance: JsValue | null): void;
    static Get<T>(configuration: IConfiguration, configureOptions: Action_1<BinderOptions> | null): T | null;
    static Get(configuration: IConfiguration, type: Type, configureOptions: Action_1<BinderOptions> | null): JsValue | null;
    static Get(configuration: IConfiguration, type: Type): JsValue | null;
    static Get<T>(configuration: IConfiguration): T | null;
    static GetValue<T>(configuration: IConfiguration, key: string, defaultValue: T): T | null;
    static GetValue<T>(configuration: IConfiguration, key: string): T | null;
    static GetValue(configuration: IConfiguration, type: Type, key: string, defaultValue: JsValue | null): JsValue | null;
    static GetValue(configuration: IConfiguration, type: Type, key: string): JsValue | null;
}


export type ConfigurationBinder = ConfigurationBinder$instance;

export abstract class ConfigurationExtensions$instance {
    static Add<TSource extends IConfigurationSource>(builder: IConfigurationBuilder, configureSource: Action_1<TSource> | null): IConfigurationBuilder;
    static AsEnumerable(configuration: IConfiguration, makePathsRelative: boolean): IEnumerable_1<KeyValuePair_2<System_Internal.String, System_Internal.String>>;
    static AsEnumerable(configuration: IConfiguration): IEnumerable_1<KeyValuePair_2<System_Internal.String, System_Internal.String>>;
    static Exists(section: IConfigurationSection | null): boolean;
    static GetConnectionString(configuration: IConfiguration, name: string): string | null;
    static GetRequiredSection(configuration: IConfiguration, key: string): IConfigurationSection;
}


export type ConfigurationExtensions = ConfigurationExtensions$instance;

export abstract class ConfigurationPath$instance {
    static readonly KeyDelimiter: string;
    static Combine(pathSegments: IEnumerable_1<System_Internal.String>): string;
    static Combine(...pathSegments: string[]): string;
    static GetParentPath(path: string | null): string | null;
    static GetSectionKey(path: string | null): string | null;
}


export type ConfigurationPath = ConfigurationPath$instance;

export abstract class ConfigurationRootExtensions$instance {
    static GetDebugView(root: IConfigurationRoot, processValue: Func_2<ConfigurationDebugViewContext, System_Internal.String> | null): string;
    static GetDebugView(root: IConfigurationRoot): string;
}


export type ConfigurationRootExtensions = ConfigurationRootExtensions$instance;

export abstract class EnvironmentVariablesExtensions$instance {
    static AddEnvironmentVariables(builder: IConfigurationBuilder, configureSource: Action_1<EnvironmentVariablesConfigurationSource> | null): IConfigurationBuilder;
    static AddEnvironmentVariables(configurationBuilder: IConfigurationBuilder, prefix: string | null): IConfigurationBuilder;
    static AddEnvironmentVariables(configurationBuilder: IConfigurationBuilder): IConfigurationBuilder;
}


export type EnvironmentVariablesExtensions = EnvironmentVariablesExtensions$instance;

export abstract class FileConfigurationExtensions$instance {
    static GetFileLoadExceptionHandler(builder: IConfigurationBuilder): Action_1<FileLoadExceptionContext> | null;
    static GetFileProvider(builder: IConfigurationBuilder): IFileProvider;
    static SetBasePath(builder: IConfigurationBuilder, basePath: string): IConfigurationBuilder;
    static SetFileLoadExceptionHandler(builder: IConfigurationBuilder, handler: Action_1<FileLoadExceptionContext>): IConfigurationBuilder;
    static SetFileProvider(builder: IConfigurationBuilder, fileProvider: IFileProvider): IConfigurationBuilder;
}


export type FileConfigurationExtensions = FileConfigurationExtensions$instance;

export abstract class IniConfigurationExtensions$instance {
    static AddIniFile(builder: IConfigurationBuilder, provider: IFileProvider | null, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, configureSource: Action_1<IniConfigurationSource> | null): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddIniStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type IniConfigurationExtensions = IniConfigurationExtensions$instance;

export abstract class JsonConfigurationExtensions$instance {
    static AddJsonFile(builder: IConfigurationBuilder, provider: IFileProvider | null, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, configureSource: Action_1<JsonConfigurationSource> | null): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddJsonStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type JsonConfigurationExtensions = JsonConfigurationExtensions$instance;

export abstract class KeyPerFileConfigurationBuilderExtensions$instance {
    static AddKeyPerFile(builder: IConfigurationBuilder, configureSource: Action_1<KeyPerFileConfigurationSource>): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string, optional: boolean): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string): IConfigurationBuilder;
}


export type KeyPerFileConfigurationBuilderExtensions = KeyPerFileConfigurationBuilderExtensions$instance;

export abstract class MemoryConfigurationBuilderExtensions$instance {
    static AddInMemoryCollection(configurationBuilder: IConfigurationBuilder, initialData: IEnumerable_1<KeyValuePair_2<System_Internal.String, System_Internal.String>> | null): IConfigurationBuilder;
    static AddInMemoryCollection(configurationBuilder: IConfigurationBuilder): IConfigurationBuilder;
}


export type MemoryConfigurationBuilderExtensions = MemoryConfigurationBuilderExtensions$instance;

export abstract class UserSecretsConfigurationExtensions$instance {
    static AddUserSecrets<T>(configuration: IConfigurationBuilder, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets<T>(configuration: IConfigurationBuilder, optional: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly, optional: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, userSecretsId: string, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, userSecretsId: string): IConfigurationBuilder;
    static AddUserSecrets<T>(configuration: IConfigurationBuilder): IConfigurationBuilder;
}


export type UserSecretsConfigurationExtensions = UserSecretsConfigurationExtensions$instance;

export abstract class XmlConfigurationExtensions$instance {
    static AddXmlFile(builder: IConfigurationBuilder, provider: IFileProvider | null, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, configureSource: Action_1<XmlConfigurationSource> | null): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddXmlStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type XmlConfigurationExtensions = XmlConfigurationExtensions$instance;

