// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration
// Assembly: Microsoft.Extensions.Configuration, Microsoft.Extensions.Configuration.Abstractions, Microsoft.Extensions.Configuration.Binder, Microsoft.Extensions.Configuration.CommandLine, Microsoft.Extensions.Configuration.EnvironmentVariables, Microsoft.Extensions.Configuration.FileExtensions, Microsoft.Extensions.Configuration.Ini, Microsoft.Extensions.Configuration.Json, Microsoft.Extensions.Configuration.KeyPerFile, Microsoft.Extensions.Configuration.UserSecrets, Microsoft.Extensions.Configuration.Xml

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { CommandLineConfigurationSource } from "../../Microsoft.Extensions.Configuration.CommandLine/internal/index.js";
import type { EnvironmentVariablesConfigurationSource } from "../../Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js";
import type { IniConfigurationSource } from "../../Microsoft.Extensions.Configuration.Ini/internal/index.js";
import type { JsonConfigurationSource } from "../../Microsoft.Extensions.Configuration.Json/internal/index.js";
import type { KeyPerFileConfigurationSource } from "../../Microsoft.Extensions.Configuration.KeyPerFile/internal/index.js";
import type { XmlConfigurationSource } from "../../Microsoft.Extensions.Configuration.Xml/internal/index.js";
import type { IFileProvider } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import * as Microsoft_Extensions_Primitives_Internal from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IComparer, IDictionary, IEnumerable, IList, KeyValuePair } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Stream } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Attribute, Boolean as ClrBoolean, Exception, Func, IDisposable, Int32, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System.js";
import type { Assembly } from "@tsonic/dotnet/System.Reflection.js";

export interface IConfiguration$instance {
    get Item(): string | undefined;
    set Item(value: string);
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export type IConfiguration = IConfiguration$instance;

export interface IConfigurationBuilder$instance {
    readonly Properties: IDictionary<System_Internal.String, unknown>;
    readonly Sources: IList<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
}


export type IConfigurationBuilder = IConfigurationBuilder$instance;

export interface IConfigurationManager$instance extends IConfiguration, IConfigurationBuilder {
    get Item(): string | undefined;
    set Item(value: string);
    readonly Properties: IDictionary<System_Internal.String, unknown>;
    readonly Sources: IList<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export interface IConfigurationManager$instance extends IConfiguration$instance, IConfigurationBuilder$instance {}

export type IConfigurationManager = IConfigurationManager$instance;

export interface IConfigurationProvider$instance {
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    TryGet(key: string, value: string): boolean;
}


export type IConfigurationProvider = IConfigurationProvider$instance;

export interface IConfigurationRoot$instance extends IConfiguration {
    readonly Providers: IEnumerable<IConfigurationProvider>;
    get Item(): string | undefined;
    set Item(value: string);
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    Reload(): void;
}


export interface IConfigurationRoot$instance extends IConfiguration$instance {}

export type IConfigurationRoot = IConfigurationRoot$instance;

export interface IConfigurationSection$instance extends IConfiguration {
    readonly Key: string;
    readonly Path: string;
    Value: string;
    get Item(): string | undefined;
    set Item(value: string);
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
}


export interface IConfigurationSection$instance extends IConfiguration$instance {}

export type IConfigurationSection = IConfigurationSection$instance;

export interface IConfigurationSource$instance {
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export type IConfigurationSource = IConfigurationSource$instance;

export interface ConfigurationDebugViewContext$instance {
    readonly ConfigurationProvider: IConfigurationProvider;
    readonly Key: string;
    readonly Path: string;
    readonly Value: string | undefined;
}


export const ConfigurationDebugViewContext: {
    new(path: string, key: string, value: string, configurationProvider: IConfigurationProvider): ConfigurationDebugViewContext;
};


export type ConfigurationDebugViewContext = ConfigurationDebugViewContext$instance;

export interface BinderOptions$instance {
    BindNonPublicProperties: boolean;
    ErrorOnUnknownConfiguration: boolean;
}


export const BinderOptions: {
    new(): BinderOptions;
};


export type BinderOptions = BinderOptions$instance;

export interface ChainedConfigurationProvider$instance {
    readonly Configuration: IConfiguration;
    Dispose(): void;
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    TryGet(key: string, value: string): boolean;
}


export const ChainedConfigurationProvider: {
    new(source: ChainedConfigurationSource): ChainedConfigurationProvider;
};


export interface __ChainedConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export interface ChainedConfigurationProvider$instance extends IConfigurationProvider$instance {}

export type ChainedConfigurationProvider = ChainedConfigurationProvider$instance & __ChainedConfigurationProvider$views;


export interface ChainedConfigurationSource$instance {
    Configuration: IConfiguration;
    ShouldDisposeConfiguration: boolean;
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const ChainedConfigurationSource: {
    new(): ChainedConfigurationSource;
};


export interface __ChainedConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export interface ChainedConfigurationSource$instance extends IConfigurationSource$instance {}

export type ChainedConfigurationSource = ChainedConfigurationSource$instance & __ChainedConfigurationSource$views;


export interface ConfigurationBuilder$instance {
    readonly Properties: IDictionary<System_Internal.String, unknown>;
    readonly Sources: IList<IConfigurationSource>;
    Add(source: IConfigurationSource): IConfigurationBuilder;
    Build(): IConfigurationRoot;
}


export const ConfigurationBuilder: {
    new(): ConfigurationBuilder;
};


export interface __ConfigurationBuilder$views {
    As_IConfigurationBuilder(): IConfigurationBuilder$instance;
}

export interface ConfigurationBuilder$instance extends IConfigurationBuilder$instance {}

export type ConfigurationBuilder = ConfigurationBuilder$instance & __ConfigurationBuilder$views;


export interface ConfigurationKeyComparer$instance {
    Compare(x: string, y: string): int;
}


export const ConfigurationKeyComparer: {
    new(): ConfigurationKeyComparer;
    readonly Instance: ConfigurationKeyComparer;
};


export type ConfigurationKeyComparer = ConfigurationKeyComparer$instance;

export interface ConfigurationKeyNameAttribute$instance extends Attribute {
    readonly Name: string;
}


export const ConfigurationKeyNameAttribute: {
    new(name: string): ConfigurationKeyNameAttribute;
};


export type ConfigurationKeyNameAttribute = ConfigurationKeyNameAttribute$instance;

export interface ConfigurationManager$instance {
    get Item(): string | undefined;
    set Item(value: string);
    readonly Sources: IList<IConfigurationSource>;
    Dispose(): void;
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetSection(key: string): IConfigurationSection;
}


export const ConfigurationManager: {
    new(): ConfigurationManager;
};


export interface __ConfigurationManager$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationBuilder(): IConfigurationBuilder$instance;
    As_IConfigurationRoot(): IConfigurationRoot$instance;
}

export type ConfigurationManager = ConfigurationManager$instance & __ConfigurationManager$views;


export interface ConfigurationProvider$instance {
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    ToString(): string;
    TryGet(key: string, value: string): boolean;
}


export const ConfigurationProvider: {
    new(): ConfigurationProvider;
};


export interface __ConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export interface ConfigurationProvider$instance extends IConfigurationProvider$instance {}

export type ConfigurationProvider = ConfigurationProvider$instance & __ConfigurationProvider$views;


export interface ConfigurationReloadToken$instance {
    ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
    OnReload(): void;
    RegisterChangeCallback(callback: Action<unknown>, state: unknown): IDisposable;
}


export const ConfigurationReloadToken: {
    new(): ConfigurationReloadToken;
};


export interface __ConfigurationReloadToken$views {
    As_IChangeToken(): Microsoft_Extensions_Primitives_Internal.IChangeToken$instance;
}

export type ConfigurationReloadToken = ConfigurationReloadToken$instance & __ConfigurationReloadToken$views;


export interface ConfigurationRoot$instance {
    get Item(): string | undefined;
    set Item(value: string);
    readonly Providers: IEnumerable<IConfigurationProvider>;
    Dispose(): void;
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    Reload(): void;
}


export const ConfigurationRoot: {
    new(providers: IList<IConfigurationProvider>): ConfigurationRoot;
};


export interface __ConfigurationRoot$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationRoot(): IConfigurationRoot$instance;
}

export type ConfigurationRoot = ConfigurationRoot$instance & __ConfigurationRoot$views;


export interface ConfigurationSection$instance {
    get Item(): string | undefined;
    set Item(value: string);
    readonly Key: string;
    readonly Path: string;
    Value: string;
    GetChildren(): IEnumerable<IConfigurationSection>;
    GetReloadToken(): IChangeToken;
    GetSection(key: string): IConfigurationSection;
    TryGetValue(key: string, value: string): boolean;
}


export const ConfigurationSection: {
    new(root: IConfigurationRoot, path: string): ConfigurationSection;
};


export interface __ConfigurationSection$views {
    As_IConfiguration(): IConfiguration$instance;
    As_IConfigurationSection(): IConfigurationSection$instance;
}

export type ConfigurationSection = ConfigurationSection$instance & __ConfigurationSection$views;


export abstract class FileConfigurationProvider$protected {
    protected Dispose(disposing: boolean): void;
}


export interface FileConfigurationProvider$instance extends FileConfigurationProvider$protected, ConfigurationProvider$instance {
    readonly Source: FileConfigurationSource;
    Dispose(): void;
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    ToString(): string;
    TryGet(key: string, value: string): boolean;
}


export const FileConfigurationProvider: {
    new(source: FileConfigurationSource): FileConfigurationProvider;
};


export interface __FileConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type FileConfigurationProvider = FileConfigurationProvider$instance & __FileConfigurationProvider$views;


export interface FileConfigurationSource$instance {
    get FileProvider(): IFileProvider | undefined;
    set FileProvider(value: IFileProvider);
    get OnLoadException(): Action<FileLoadExceptionContext> | undefined;
    set OnLoadException(value: Action<FileLoadExceptionContext>);
    Optional: boolean;
    Path: string;
    ReloadDelay: int;
    ReloadOnChange: boolean;
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
    EnsureDefaults(builder: IConfigurationBuilder): void;
    ResolveFileProvider(): void;
}


export const FileConfigurationSource: {
    new(): FileConfigurationSource;
};


export interface __FileConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export interface FileConfigurationSource$instance extends IConfigurationSource$instance {}

export type FileConfigurationSource = FileConfigurationSource$instance & __FileConfigurationSource$views;


export interface FileLoadExceptionContext$instance {
    Exception: Exception;
    Ignore: boolean;
    Provider: FileConfigurationProvider;
}


export const FileLoadExceptionContext: {
    new(): FileLoadExceptionContext;
};


export type FileLoadExceptionContext = FileLoadExceptionContext$instance;

export interface StreamConfigurationProvider$instance extends ConfigurationProvider$instance {
    readonly Source: StreamConfigurationSource;
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    TryGet(key: string, value: string): boolean;
}


export const StreamConfigurationProvider: {
    new(source: StreamConfigurationSource): StreamConfigurationProvider;
};


export interface __StreamConfigurationProvider$views {
    As_IConfigurationProvider(): IConfigurationProvider$instance;
}

export type StreamConfigurationProvider = StreamConfigurationProvider$instance & __StreamConfigurationProvider$views;


export interface StreamConfigurationSource$instance {
    get Stream(): Stream | undefined;
    set Stream(value: Stream);
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const StreamConfigurationSource: {
    new(): StreamConfigurationSource;
};


export interface __StreamConfigurationSource$views {
    As_IConfigurationSource(): IConfigurationSource$instance;
}

export interface StreamConfigurationSource$instance extends IConfigurationSource$instance {}

export type StreamConfigurationSource = StreamConfigurationSource$instance & __StreamConfigurationSource$views;


export abstract class ChainedBuilderExtensions$instance {
    static AddConfiguration(configurationBuilder: IConfigurationBuilder, config: IConfiguration, shouldDisposeConfiguration: boolean): IConfigurationBuilder;
    static AddConfiguration(configurationBuilder: IConfigurationBuilder, config: IConfiguration): IConfigurationBuilder;
}


export type ChainedBuilderExtensions = ChainedBuilderExtensions$instance;

export abstract class CommandLineConfigurationExtensions$instance {
    static AddCommandLine(builder: IConfigurationBuilder, configureSource: Action<CommandLineConfigurationSource>): IConfigurationBuilder;
    static AddCommandLine(configurationBuilder: IConfigurationBuilder, args: string[], switchMappings: IDictionary<System_Internal.String, System_Internal.String>): IConfigurationBuilder;
    static AddCommandLine(configurationBuilder: IConfigurationBuilder, args: string[]): IConfigurationBuilder;
}


export type CommandLineConfigurationExtensions = CommandLineConfigurationExtensions$instance;

export abstract class ConfigurationBinder$instance {
    static Bind(configuration: IConfiguration, instance: unknown, configureOptions: Action<BinderOptions>): void;
    static Bind(configuration: IConfiguration, instance: unknown): void;
    static Bind(configuration: IConfiguration, key: string, instance: unknown): void;
    static Get<T>(configuration: IConfiguration, configureOptions: Action<BinderOptions>): T | undefined;
    static Get(configuration: IConfiguration, type: Type, configureOptions: Action<BinderOptions>): unknown | undefined;
    static Get(configuration: IConfiguration, type: Type): unknown | undefined;
    static Get<T>(configuration: IConfiguration): T | undefined;
    static GetValue<T>(configuration: IConfiguration, key: string, defaultValue: T): T | undefined;
    static GetValue<T>(configuration: IConfiguration, key: string): T | undefined;
    static GetValue(configuration: IConfiguration, type: Type, key: string, defaultValue: unknown): unknown | undefined;
    static GetValue(configuration: IConfiguration, type: Type, key: string): unknown | undefined;
}


export type ConfigurationBinder = ConfigurationBinder$instance;

export abstract class ConfigurationExtensions$instance {
    static Add<TSource extends IConfigurationSource>(builder: IConfigurationBuilder, configureSource: Action<TSource>): IConfigurationBuilder;
    static AsEnumerable(configuration: IConfiguration, makePathsRelative: boolean): IEnumerable<KeyValuePair<System_Internal.String, System_Internal.String>>;
    static AsEnumerable(configuration: IConfiguration): IEnumerable<KeyValuePair<System_Internal.String, System_Internal.String>>;
    static Exists(section: IConfigurationSection): boolean;
    static GetConnectionString(configuration: IConfiguration, name: string): string | undefined;
    static GetRequiredSection(configuration: IConfiguration, key: string): IConfigurationSection;
}


export type ConfigurationExtensions = ConfigurationExtensions$instance;

export abstract class ConfigurationPath$instance {
    static readonly KeyDelimiter: string;
    static Combine(pathSegments: IEnumerable<System_Internal.String>): string;
    static Combine(...pathSegments: string[]): string;
    static GetParentPath(path: string): string | undefined;
    static GetSectionKey(path: string): string | undefined;
}


export type ConfigurationPath = ConfigurationPath$instance;

export abstract class ConfigurationRootExtensions$instance {
    static GetDebugView(root: IConfigurationRoot, processValue: Func<ConfigurationDebugViewContext, System_Internal.String>): string;
    static GetDebugView(root: IConfigurationRoot): string;
}


export type ConfigurationRootExtensions = ConfigurationRootExtensions$instance;

export abstract class EnvironmentVariablesExtensions$instance {
    static AddEnvironmentVariables(builder: IConfigurationBuilder, configureSource: Action<EnvironmentVariablesConfigurationSource>): IConfigurationBuilder;
    static AddEnvironmentVariables(configurationBuilder: IConfigurationBuilder, prefix: string): IConfigurationBuilder;
    static AddEnvironmentVariables(configurationBuilder: IConfigurationBuilder): IConfigurationBuilder;
}


export type EnvironmentVariablesExtensions = EnvironmentVariablesExtensions$instance;

export abstract class FileConfigurationExtensions$instance {
    static GetFileLoadExceptionHandler(builder: IConfigurationBuilder): Action<FileLoadExceptionContext> | undefined;
    static GetFileProvider(builder: IConfigurationBuilder): IFileProvider;
    static SetBasePath(builder: IConfigurationBuilder, basePath: string): IConfigurationBuilder;
    static SetFileLoadExceptionHandler(builder: IConfigurationBuilder, handler: Action<FileLoadExceptionContext>): IConfigurationBuilder;
    static SetFileProvider(builder: IConfigurationBuilder, fileProvider: IFileProvider): IConfigurationBuilder;
}


export type FileConfigurationExtensions = FileConfigurationExtensions$instance;

export abstract class IniConfigurationExtensions$instance {
    static AddIniFile(builder: IConfigurationBuilder, provider: IFileProvider, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, configureSource: Action<IniConfigurationSource>): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddIniFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddIniStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type IniConfigurationExtensions = IniConfigurationExtensions$instance;

export abstract class JsonConfigurationExtensions$instance {
    static AddJsonFile(builder: IConfigurationBuilder, provider: IFileProvider, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, configureSource: Action<JsonConfigurationSource>): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddJsonFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddJsonStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type JsonConfigurationExtensions = JsonConfigurationExtensions$instance;

export abstract class KeyPerFileConfigurationBuilderExtensions$instance {
    static AddKeyPerFile(builder: IConfigurationBuilder, configureSource: Action<KeyPerFileConfigurationSource>): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string, optional: boolean): IConfigurationBuilder;
    static AddKeyPerFile(builder: IConfigurationBuilder, directoryPath: string): IConfigurationBuilder;
}


export type KeyPerFileConfigurationBuilderExtensions = KeyPerFileConfigurationBuilderExtensions$instance;

export abstract class MemoryConfigurationBuilderExtensions$instance {
    static AddInMemoryCollection(configurationBuilder: IConfigurationBuilder, initialData: IEnumerable<KeyValuePair<System_Internal.String, System_Internal.String>>): IConfigurationBuilder;
    static AddInMemoryCollection(configurationBuilder: IConfigurationBuilder): IConfigurationBuilder;
}


export type MemoryConfigurationBuilderExtensions = MemoryConfigurationBuilderExtensions$instance;

export abstract class UserSecretsConfigurationExtensions$instance {
    static AddUserSecrets<T>(configuration: IConfigurationBuilder, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets<T>(configuration: IConfigurationBuilder, optional: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly, optional: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, assembly: Assembly): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, userSecretsId: string, reloadOnChange: boolean): IConfigurationBuilder;
    static AddUserSecrets(configuration: IConfigurationBuilder, userSecretsId: string): IConfigurationBuilder;
    static AddUserSecrets<T>(configuration: IConfigurationBuilder): IConfigurationBuilder;
}


export type UserSecretsConfigurationExtensions = UserSecretsConfigurationExtensions$instance;

export abstract class XmlConfigurationExtensions$instance {
    static AddXmlFile(builder: IConfigurationBuilder, provider: IFileProvider, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, configureSource: Action<XmlConfigurationSource>): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string, optional: boolean, reloadOnChange: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string, optional: boolean): IConfigurationBuilder;
    static AddXmlFile(builder: IConfigurationBuilder, path: string): IConfigurationBuilder;
    static AddXmlStream(builder: IConfigurationBuilder, stream: Stream): IConfigurationBuilder;
}


export type XmlConfigurationExtensions = XmlConfigurationExtensions$instance;

