// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Http
// Assembly: Microsoft.Extensions.Http

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, Func, IServiceProvider, Object as ClrObject, String as ClrString, TimeSpan } from "@tsonic/dotnet/System.js";
import type { DelegatingHandler, HttpClient, HttpMessageHandler } from "@tsonic/dotnet/System.Net.Http.js";

export interface IHttpMessageHandlerBuilderFilter$instance {
    Configure(next: Action<HttpMessageHandlerBuilder>): Action<HttpMessageHandlerBuilder>;
}


export type IHttpMessageHandlerBuilderFilter = IHttpMessageHandlerBuilderFilter$instance;

export interface ITypedHttpClientFactory_1$instance<TClient> {
    CreateClient(httpClient: HttpClient): TClient;
}


export type ITypedHttpClientFactory_1<TClient> = ITypedHttpClientFactory_1$instance<TClient>;

export interface HttpClientFactoryOptions$instance {
    HandlerLifetime: TimeSpan;
    readonly HttpClientActions: IList<Action<HttpClient>>;
    readonly HttpMessageHandlerBuilderActions: IList<Action<HttpMessageHandlerBuilder>>;
    ShouldRedactHeaderValue: Func<System_Internal.String, System_Internal.Boolean>;
    SuppressHandlerScope: boolean;
}


export const HttpClientFactoryOptions: {
    new(): HttpClientFactoryOptions;
};


export type HttpClientFactoryOptions = HttpClientFactoryOptions$instance;

export interface HttpMessageHandlerBuilder$instance {
    readonly AdditionalHandlers: IList<DelegatingHandler>;
    Name: string;
    PrimaryHandler: HttpMessageHandler;
    readonly Services: IServiceProvider;
    Build(): HttpMessageHandler;
}


export const HttpMessageHandlerBuilder: {
};


export type HttpMessageHandlerBuilder = HttpMessageHandlerBuilder$instance;

