// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration.KeyPerFile
// Assembly: Microsoft.Extensions.Configuration.KeyPerFile

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as Microsoft_Extensions_Configuration_Internal from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { ConfigurationProvider, IConfigurationBuilder, IConfigurationProvider, IConfigurationSource } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { IFileProvider } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Func, IDisposable, Int32, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export interface KeyPerFileConfigurationProvider$instance extends ConfigurationProvider {
    Dispose(): void;
    GetChildKeys(earlierKeys: IEnumerable<System_Internal.String>, parentPath: string): IEnumerable<System_Internal.String>;
    GetReloadToken(): IChangeToken;
    Load(): void;
    Set(key: string, value: string): void;
    ToString(): string;
    TryGet(key: string, value: string): boolean;
}


export const KeyPerFileConfigurationProvider: {
    new(source: KeyPerFileConfigurationSource): KeyPerFileConfigurationProvider;
};


export interface __KeyPerFileConfigurationProvider$views {
    As_IConfigurationProvider(): Microsoft_Extensions_Configuration_Internal.IConfigurationProvider$instance;
}

export type KeyPerFileConfigurationProvider = KeyPerFileConfigurationProvider$instance & __KeyPerFileConfigurationProvider$views;


export interface KeyPerFileConfigurationSource$instance {
    get FileProvider(): IFileProvider | undefined;
    set FileProvider(value: IFileProvider);
    IgnoreCondition: Func<System_Internal.String, System_Internal.Boolean>;
    IgnorePrefix: string;
    Optional: boolean;
    ReloadDelay: int;
    ReloadOnChange: boolean;
    SectionDelimiter: string;
    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const KeyPerFileConfigurationSource: {
    new(): KeyPerFileConfigurationSource;
};


export interface __KeyPerFileConfigurationSource$views {
    As_IConfigurationSource(): Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance;
}

export interface KeyPerFileConfigurationSource$instance extends Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance {}

export type KeyPerFileConfigurationSource = KeyPerFileConfigurationSource$instance & __KeyPerFileConfigurationSource$views;


