// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Extensions.Logging.EventSource
// Assembly: Microsoft.Extensions.Logging.EventSource

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_Extensions_Logging_Internal from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { ILogger, ILoggerProvider } from "../../Microsoft.Extensions.Logging/internal/index.js";
import * as System_Diagnostics_Tracing_Internal from "@tsonic/dotnet/System.Diagnostics.Tracing/internal/index.js";
import type { EventCommandEventArgs, EventKeywords, EventSource } from "@tsonic/dotnet/System.Diagnostics.Tracing/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface EventSourceLoggerProvider$instance extends Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance {
    readonly __tsonic_type_Microsoft_Extensions_Logging_EventSource_EventSourceLoggerProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILoggerProvider: never;
    readonly __tsonic_iface_System_IDisposable: never;

    CreateLogger(categoryName: string): ILogger;
    Dispose(): void;
}


export const EventSourceLoggerProvider: {
    new(eventSource: LoggingEventSource): EventSourceLoggerProvider;
};


export interface __EventSourceLoggerProvider$views {
    As_ILoggerProvider(): Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance;
}

export type EventSourceLoggerProvider = EventSourceLoggerProvider$instance & __EventSourceLoggerProvider$views;


export interface LoggingEventSource$instance extends EventSource {
    readonly __tsonic_type_Microsoft_Extensions_Logging_EventSource_LoggingEventSource: never;

    readonly __tsonic_iface_System_IDisposable: never;

    OnEventCommand(command: EventCommandEventArgs): void;
}


export const LoggingEventSource: {
};


export type LoggingEventSource = LoggingEventSource$instance;

export abstract class LoggingEventSource_Keywords$instance {
    static readonly Meta: EventKeywords;
    static readonly Message: EventKeywords;
    static readonly FormattedMessage: EventKeywords;
    static readonly JsonMessage: EventKeywords;
}


export type LoggingEventSource_Keywords = LoggingEventSource_Keywords$instance;

