// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration.Memory
// Assembly: Microsoft.Extensions.Configuration

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as Microsoft_Extensions_Configuration_Internal from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { ConfigurationProvider, IConfigurationBuilder, IConfigurationProvider, IConfigurationSource } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, KeyValuePair } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export interface MemoryConfigurationProvider$instance extends ConfigurationProvider {
    add(key: string, value: string): void;
    getChildKeys(earlierKeys: IEnumerable__System_Collections_Generic<System_Internal.String>, parentPath: string): IEnumerable__System_Collections_Generic<System_Internal.String>;
    getEnumerator(): IEnumerator<KeyValuePair<System_Internal.String, System_Internal.String>>;
    getReloadToken(): IChangeToken;
    load(): void;
    set_(key: string, value: string): void;
    tryGet(key: string, value: string): boolean;
}


export const MemoryConfigurationProvider: {
    new(source: MemoryConfigurationSource): MemoryConfigurationProvider;
};


export interface __MemoryConfigurationProvider$views {
    As_IConfigurationProvider(): Microsoft_Extensions_Configuration_Internal.IConfigurationProvider$instance;
}

export type MemoryConfigurationProvider = MemoryConfigurationProvider$instance & __MemoryConfigurationProvider$views;


export interface MemoryConfigurationSource$instance {
    get initialData(): IEnumerable__System_Collections_Generic<KeyValuePair<System_Internal.String, System_Internal.String>> | undefined;
    set initialData(value: IEnumerable__System_Collections_Generic<KeyValuePair<System_Internal.String, System_Internal.String>>);
    build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const MemoryConfigurationSource: {
    new(): MemoryConfigurationSource;
};


export interface __MemoryConfigurationSource$views {
    As_IConfigurationSource(): Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance;
}

export interface MemoryConfigurationSource$instance extends Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance {}

export type MemoryConfigurationSource = MemoryConfigurationSource$instance & __MemoryConfigurationSource$views;


