// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Primitives
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Primitives/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection, IComparer, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator as IEnumerator__System_Collections_Generic, IEqualityComparer, IList, IReadOnlyCollection, IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable, IEnumerator } from '@tsonic/dotnet/System.Collections.js';
import type { Action, Boolean as ClrBoolean, Char, Func, IDisposable, IEquatable, Int32, Object as ClrObject, ReadOnlyMemory, ReadOnlySpan, String as ClrString, StringComparison, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { StringBuilder } from '@tsonic/dotnet/System.Text.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CancellationChangeToken as CancellationChangeToken } from './Microsoft.Extensions.Primitives/internal/index.js';
export { ChangeToken$instance as ChangeToken } from './Microsoft.Extensions.Primitives/internal/index.js';
export { CompositeChangeToken as CompositeChangeToken } from './Microsoft.Extensions.Primitives/internal/index.js';
export { Extensions$instance as Extensions } from './Microsoft.Extensions.Primitives/internal/index.js';
export type IChangeToken = Internal.IChangeToken;
export { InplaceStringBuilder as InplaceStringBuilder } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringSegment as StringSegment } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringSegmentComparer as StringSegmentComparer } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringTokenizer as StringTokenizer } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringValues as StringValues } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringTokenizer_Enumerator as StringTokenizer_Enumerator } from './Microsoft.Extensions.Primitives/internal/index.js';
export { StringValues_Enumerator as StringValues_Enumerator } from './Microsoft.Extensions.Primitives/internal/index.js';
