// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Abstractions
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { DirectoryInfo, FileInfo } from '@tsonic/dotnet/System.IO.js';
import type { Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DirectoryInfoBase as DirectoryInfoBase } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
export { DirectoryInfoWrapper as DirectoryInfoWrapper } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
export { FileInfoBase as FileInfoBase } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
export { FileInfoWrapper as FileInfoWrapper } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
export { FileSystemInfoBase as FileSystemInfoBase } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
