// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { DirectoryInfoBase, FileInfoBase } from './Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js';
import type { PatternMatchingResult } from './Microsoft.Extensions.FileSystemGlobbing/internal/index.js';
import type { IEnumerable, IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Action, Boolean as ClrBoolean, Object as ClrObject, String as ClrString, StringComparison, ValueType, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type ILinearPattern = Internal.ILinearPattern;
export type IPathSegment = Internal.IPathSegment;
export type IPattern = Internal.IPattern;
export type IPatternContext = Internal.IPatternContext;
export type IRaggedPattern = Internal.IRaggedPattern;
export { MatcherContext as MatcherContext } from './Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js';
export { PatternTestResult as PatternTestResult } from './Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js';
