// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration.UserSecrets
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Configuration.UserSecrets/internal/index.js';

// Cross-namespace type imports for constraints
import type { Attribute, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { PathHelper as PathHelper } from './Microsoft.Extensions.Configuration.UserSecrets/internal/index.js';
export { UserSecretsIdAttribute as UserSecretsIdAttribute } from './Microsoft.Extensions.Configuration.UserSecrets/internal/index.js';
