// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.WebEncoders
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.WebEncoders/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { Object as ClrObject } from '@tsonic/dotnet/System.js';
import type { TextEncoderSettings } from '@tsonic/dotnet/System.Text.Encodings.Web.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { WebEncoderOptions as WebEncoderOptions } from './Microsoft.Extensions.WebEncoders/internal/index.js';
