// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Diagnostics.Metrics
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';

// Cross-namespace type imports for constraints
import type { IConfiguration } from './Microsoft.Extensions.Configuration/internal/index.js';
import type { IServiceCollection } from './Microsoft.Extensions.DependencyInjection/internal/index.js';
import type { IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Instrument, MeasurementCallback } from '@tsonic/dotnet/System.Diagnostics.Metrics.js';
import type { Boolean as ClrBoolean, Byte, Decimal, Double, Enum, IComparable, IConvertible, IFormattable, Int16, Int32, Int64, ISpanFormattable, Object as ClrObject, Single, String as ClrString, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { MetricsBuilderConfigurationExtensions$instance as MetricsBuilderConfigurationExtensions } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export { ConsoleMetrics$instance as ConsoleMetrics } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export { MetricsBuilderConsoleExtensions$instance as MetricsBuilderConsoleExtensions } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export type IMetricsBuilder = Internal.IMetricsBuilder;
export type IMetricsListener = Internal.IMetricsListener;
export { InstrumentRule as InstrumentRule } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export type IObservableInstrumentsSource = Internal.IObservableInstrumentsSource;
export { MeasurementHandlers as MeasurementHandlers } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export { MeterScope as MeterScope } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export { MetricsBuilderExtensions$instance as MetricsBuilderExtensions } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
export { MetricsOptions as MetricsOptions } from './Microsoft.Extensions.Diagnostics.Metrics/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_Extensions_Diagnostics_Metrics as ExtensionMethods } from './__internal/extensions/index.js';

