// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Configuration/internal/index.js';

// Cross-namespace type imports for constraints
import type { CommandLineConfigurationSource } from './Microsoft.Extensions.Configuration.CommandLine/internal/index.js';
import type { EnvironmentVariablesConfigurationSource } from './Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js';
import type { IniConfigurationSource } from './Microsoft.Extensions.Configuration.Ini/internal/index.js';
import type { JsonConfigurationSource } from './Microsoft.Extensions.Configuration.Json/internal/index.js';
import type { KeyPerFileConfigurationSource } from './Microsoft.Extensions.Configuration.KeyPerFile/internal/index.js';
import type { XmlConfigurationSource } from './Microsoft.Extensions.Configuration.Xml/internal/index.js';
import type { IFileProvider } from './Microsoft.Extensions.FileProviders/internal/index.js';
import type { IChangeToken } from './Microsoft.Extensions.Primitives/internal/index.js';
import type { IComparer, IDictionary, IEnumerable, IList, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Action, Attribute, Boolean as ClrBoolean, Exception, Func, IDisposable, Int32, Object as ClrObject, String as ClrString, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Assembly } from '@tsonic/dotnet/System.Reflection.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ChainedBuilderExtensions$instance as ChainedBuilderExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ChainedConfigurationProvider as ChainedConfigurationProvider } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ChainedConfigurationSource as ChainedConfigurationSource } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationBuilder as ConfigurationBuilder } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationKeyComparer as ConfigurationKeyComparer } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationManager as ConfigurationManager } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationProvider as ConfigurationProvider } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationReloadToken as ConfigurationReloadToken } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationRoot as ConfigurationRoot } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationSection as ConfigurationSection } from './Microsoft.Extensions.Configuration/internal/index.js';
export { MemoryConfigurationBuilderExtensions$instance as MemoryConfigurationBuilderExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { StreamConfigurationProvider as StreamConfigurationProvider } from './Microsoft.Extensions.Configuration/internal/index.js';
export { StreamConfigurationSource as StreamConfigurationSource } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationDebugViewContext as ConfigurationDebugViewContext } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationExtensions$instance as ConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationKeyNameAttribute as ConfigurationKeyNameAttribute } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationPath$instance as ConfigurationPath } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationRootExtensions$instance as ConfigurationRootExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export type IConfiguration = Internal.IConfiguration;
export type IConfigurationBuilder = Internal.IConfigurationBuilder;
export type IConfigurationManager = Internal.IConfigurationManager;
export type IConfigurationProvider = Internal.IConfigurationProvider;
export type IConfigurationRoot = Internal.IConfigurationRoot;
export type IConfigurationSection = Internal.IConfigurationSection;
export type IConfigurationSource = Internal.IConfigurationSource;
export { BinderOptions as BinderOptions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { ConfigurationBinder$instance as ConfigurationBinder } from './Microsoft.Extensions.Configuration/internal/index.js';
export { CommandLineConfigurationExtensions$instance as CommandLineConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { EnvironmentVariablesExtensions$instance as EnvironmentVariablesExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { FileConfigurationExtensions$instance as FileConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { FileConfigurationProvider as FileConfigurationProvider } from './Microsoft.Extensions.Configuration/internal/index.js';
export { FileConfigurationSource as FileConfigurationSource } from './Microsoft.Extensions.Configuration/internal/index.js';
export { FileLoadExceptionContext as FileLoadExceptionContext } from './Microsoft.Extensions.Configuration/internal/index.js';
export { IniConfigurationExtensions$instance as IniConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { JsonConfigurationExtensions$instance as JsonConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { KeyPerFileConfigurationBuilderExtensions$instance as KeyPerFileConfigurationBuilderExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { UserSecretsConfigurationExtensions$instance as UserSecretsConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
export { XmlConfigurationExtensions$instance as XmlConfigurationExtensions } from './Microsoft.Extensions.Configuration/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_Extensions_Configuration as ExtensionMethods } from './__internal/extensions/index.js';

