// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Caching.Hybrid
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Caching.Hybrid/internal/index.js';

// Cross-namespace type imports for constraints
import type { IBufferWriter, ReadOnlySequence } from '@tsonic/dotnet/System.Buffers.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Byte, Char, Enum, Func, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, ReadOnlySpan, String as ClrString, TimeSpan, Void } from '@tsonic/dotnet/System.js';
import type { DefaultInterpolatedStringHandler } from '@tsonic/dotnet/System.Runtime.CompilerServices.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HybridCache as HybridCache } from './Microsoft.Extensions.Caching.Hybrid/internal/index.js';
export { HybridCacheEntryFlags as HybridCacheEntryFlags } from './Microsoft.Extensions.Caching.Hybrid/internal/index.js';
export { HybridCacheEntryOptions as HybridCacheEntryOptions } from './Microsoft.Extensions.Caching.Hybrid/internal/index.js';
export type IHybridCacheSerializer<T> = Internal.IHybridCacheSerializer_1<T>;
export type IHybridCacheSerializerFactory = Internal.IHybridCacheSerializerFactory;
