// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ConfigurationProvider, IConfigurationBuilder, IConfigurationProvider, IConfigurationSource } from './Microsoft.Extensions.Configuration/internal/index.js';
import type { IChangeToken } from './Microsoft.Extensions.Primitives/internal/index.js';
import type { IDictionary, IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { EnvironmentVariablesConfigurationProvider as EnvironmentVariablesConfigurationProvider } from './Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js';
export { EnvironmentVariablesConfigurationSource as EnvironmentVariablesConfigurationSource } from './Microsoft.Extensions.Configuration.EnvironmentVariables/internal/index.js';
