// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.WebEncoders.Testing
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.WebEncoders.Testing/internal/index.js';

// Cross-namespace type imports for constraints
import type { TextWriter } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, Char, Int32, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { HtmlEncoder, JavaScriptEncoder, UrlEncoder } from '@tsonic/dotnet/System.Text.Encodings.Web.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HtmlTestEncoder as HtmlTestEncoder } from './Microsoft.Extensions.WebEncoders.Testing/internal/index.js';
export { JavaScriptTestEncoder as JavaScriptTestEncoder } from './Microsoft.Extensions.WebEncoders.Testing/internal/index.js';
export { UrlTestEncoder as UrlTestEncoder } from './Microsoft.Extensions.WebEncoders.Testing/internal/index.js';
