// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.WebEncoders.Testing
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace Microsoft.Extensions.WebEncoders.Testing in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
