// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';

// Cross-namespace type imports for constraints
import type { IPathSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js';
import type { List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, StringComparison } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CurrentPathSegment as CurrentPathSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';
export { LiteralPathSegment as LiteralPathSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';
export { ParentPathSegment as ParentPathSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';
export { RecursiveWildcardSegment as RecursiveWildcardSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';
export { WildcardPathSegment as WildcardPathSegment } from './Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments/internal/index.js';
