// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { DateTimeOffset, Object as ClrObject } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type ISystemClock = Internal.ISystemClock;
export { SystemClock as SystemClock } from './Microsoft.Extensions.Internal/internal/index.js';
