// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { IPattern } from './Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js';
import type { Object as ClrObject, String as ClrString, StringComparison } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { PatternBuilder as PatternBuilder } from './Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns/internal/index.js';
