// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Logging.Debug
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.Logging.Debug/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ILogger, ILoggerProvider } from './Microsoft.Extensions.Logging/internal/index.js';
import type { IDisposable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DebugLoggerProvider as DebugLoggerProvider } from './Microsoft.Extensions.Logging.Debug/internal/index.js';
