// Generated by tsbindgen - Architecture
// Namespace: System.Security.Cryptography
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.Cryptography/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ICollection, IEnumerable, IEnumerator } from '@tsonic/dotnet/System.Collections.js';
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { AsnEncodedData, AsnEncodedDataCollection, Oid } from '@tsonic/dotnet/System.Security.Cryptography.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CryptographicAttributeObject as CryptographicAttributeObject } from './System.Security.Cryptography/internal/index.js';
export { CryptographicAttributeObjectCollection as CryptographicAttributeObjectCollection } from './System.Security.Cryptography/internal/index.js';
export { CryptographicAttributeObjectEnumerator as CryptographicAttributeObjectEnumerator } from './System.Security.Cryptography/internal/index.js';
