// Generated by tsbindgen - Architecture
// Namespace: System.Diagnostics.Eventing.Reader
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Diagnostics.Eventing.Reader/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable, IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { CultureInfo } from '@tsonic/dotnet/System.Globalization.js';
import type { SeekOrigin } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, Byte, DateTime, Enum, EventArgs, EventHandler, Exception, Guid, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, TimeSpan, Uri, Void } from '@tsonic/dotnet/System.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { SecureString } from '@tsonic/dotnet/System.Security.js';
import type { SecurityIdentifier } from '@tsonic/dotnet/System.Security.Principal.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { EventBookmark as EventBookmark } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventKeyword as EventKeyword } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLevel as EventLevel } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogConfiguration as EventLogConfiguration } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogException as EventLogException } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogInformation as EventLogInformation } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogInvalidDataException as EventLogInvalidDataException } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogIsolation as EventLogIsolation } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogLink as EventLogLink } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogMode as EventLogMode } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogNotFoundException as EventLogNotFoundException } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogPropertySelector as EventLogPropertySelector } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogProviderDisabledException as EventLogProviderDisabledException } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogQuery as EventLogQuery } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogReader as EventLogReader } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogReadingException as EventLogReadingException } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogRecord as EventLogRecord } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogSession as EventLogSession } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogStatus as EventLogStatus } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogType as EventLogType } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventLogWatcher as EventLogWatcher } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventMetadata as EventMetadata } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventOpcode as EventOpcode } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventProperty as EventProperty } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventRecord as EventRecord } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventRecordWrittenEventArgs as EventRecordWrittenEventArgs } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { EventTask as EventTask } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { PathType as PathType } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { ProviderMetadata as ProviderMetadata } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { SessionAuthentication as SessionAuthentication } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { StandardEventKeywords as StandardEventKeywords } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { StandardEventLevel as StandardEventLevel } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { StandardEventOpcode as StandardEventOpcode } from './System.Diagnostics.Eventing.Reader/internal/index.js';
export { StandardEventTask as StandardEventTask } from './System.Diagnostics.Eventing.Reader/internal/index.js';
