// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing
// Assembly: Microsoft.Extensions.FileSystemGlobbing

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_Extensions_FileSystemGlobbing_Abstractions_Internal from "../../Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js";
import type { DirectoryInfoBase, FileInfoBase, FileSystemInfoBase } from "../../Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js";
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, IEquatable_1, Int32, Object as ClrObject, String as ClrString, StringComparison, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface FilePatternMatch$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_FilePatternMatch: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Path: string;
    readonly Stem: string;
    Equals(other: FilePatternMatch): boolean;
    Equals(obj: JsValue | null): boolean;
    GetHashCode(): int;
}


export const FilePatternMatch: {
    new(path: string, stem: string): FilePatternMatch;
};


export type FilePatternMatch = FilePatternMatch$instance;

export interface InMemoryDirectoryInfo$instance extends DirectoryInfoBase {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_InMemoryDirectoryInfo: never;

    readonly FullName: string;
    readonly Name: string;
    readonly ParentDirectory: DirectoryInfoBase | null;
    EnumerateFileSystemInfos(): IEnumerable_1<FileSystemInfoBase>;
    GetDirectory(path: string): DirectoryInfoBase;
    GetFile(path: string): FileInfoBase | null;
}


export const InMemoryDirectoryInfo: {
    new(rootDir: string, files: IEnumerable_1<System_Internal.String> | null): InMemoryDirectoryInfo;
};


export type InMemoryDirectoryInfo = InMemoryDirectoryInfo$instance;

export interface Matcher$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Matcher: never;

    AddExclude(pattern: string): Matcher;
    AddInclude(pattern: string): Matcher;
    Execute(directoryInfo: DirectoryInfoBase): PatternMatchingResult;
}


export const Matcher: {
    new(): Matcher;
    new(comparisonType: StringComparison): Matcher;
    new(comparisonType: StringComparison, preserveFilterOrder: boolean): Matcher;
};


export type Matcher = Matcher$instance;

export interface PatternMatchingResult$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_PatternMatchingResult: never;

    Files: IEnumerable_1<FilePatternMatch>;
    readonly HasMatches: boolean;
}


export const PatternMatchingResult: {
    new(files: IEnumerable_1<FilePatternMatch>): PatternMatchingResult;
    new(files: IEnumerable_1<FilePatternMatch>, hasMatches: boolean): PatternMatchingResult;
};


export type PatternMatchingResult = PatternMatchingResult$instance;

export abstract class MatcherExtensions$instance {
    static AddExcludePatterns(matcher: Matcher, ...excludePatternsGroups: IEnumerable_1<System_Internal.String>[]): void;
    static AddIncludePatterns(matcher: Matcher, ...includePatternsGroups: IEnumerable_1<System_Internal.String>[]): void;
    static GetResultsInFullPath(matcher: Matcher, directoryPath: string): IEnumerable_1<System_Internal.String>;
    static Match(matcher: Matcher, files: IEnumerable_1<System_Internal.String> | null): PatternMatchingResult;
    static Match(matcher: Matcher, rootDir: string, files: IEnumerable_1<System_Internal.String> | null): PatternMatchingResult;
    static Match(matcher: Matcher, rootDir: string, file: string): PatternMatchingResult;
    static Match(matcher: Matcher, file: string): PatternMatchingResult;
}


export type MatcherExtensions = MatcherExtensions$instance;

