// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Abstractions
// Assembly: Microsoft.Extensions.FileSystemGlobbing

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { DirectoryInfo, FileInfo } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export interface DirectoryInfoBase$instance extends FileSystemInfoBase$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_DirectoryInfoBase: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileSystemInfoBase: never;

    EnumerateFileSystemInfos(): IEnumerable_1<FileSystemInfoBase>;
    GetDirectory(path: string): DirectoryInfoBase | null;
    GetFile(path: string): FileInfoBase | null;
}


export const DirectoryInfoBase: {
};


export type DirectoryInfoBase = DirectoryInfoBase$instance;

export interface DirectoryInfoWrapper$instance extends DirectoryInfoBase$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_DirectoryInfoBase: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_DirectoryInfoWrapper: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileSystemInfoBase: never;

    EnumerateFileSystemInfos: DirectoryInfoBase$instance["EnumerateFileSystemInfos"] & (() => IEnumerable_1<FileSystemInfoBase>);
    GetDirectory: DirectoryInfoBase$instance["GetDirectory"] & ((name: string) => DirectoryInfoBase | null);
    GetFile: DirectoryInfoBase$instance["GetFile"] & ((name: string) => FileInfoBase);
}


export const DirectoryInfoWrapper: {
    new(directoryInfo: DirectoryInfo): DirectoryInfoWrapper;
};


export type DirectoryInfoWrapper = DirectoryInfoWrapper$instance;

export interface FileInfoBase$instance extends FileSystemInfoBase$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileInfoBase: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileSystemInfoBase: never;

}


export const FileInfoBase: {
};


export type FileInfoBase = FileInfoBase$instance;

export interface FileInfoWrapper$instance extends FileInfoBase$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileInfoBase: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileInfoWrapper: never;
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileSystemInfoBase: never;

}


export const FileInfoWrapper: {
    new(fileInfo: FileInfo): FileInfoWrapper;
};


export type FileInfoWrapper = FileInfoWrapper$instance;

export interface FileSystemInfoBase$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Abstractions_FileSystemInfoBase: never;

    readonly FullName: string;
    readonly Name: string;
    readonly ParentDirectory: DirectoryInfoBase | null;
}


export const FileSystemInfoBase: {
};


export type FileSystemInfoBase = FileSystemInfoBase$instance;
