// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Abstractions
// Assembly: Microsoft.Extensions.FileSystemGlobbing

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DirectoryInfo, FileInfo } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export interface DirectoryInfoBase$instance extends FileSystemInfoBase {
    enumerateFileSystemInfos(): IEnumerable<FileSystemInfoBase>;
    getDirectory(path: string): DirectoryInfoBase | undefined;
    getFile(path: string): FileInfoBase | undefined;
}


export const DirectoryInfoBase: {
};


export type DirectoryInfoBase = DirectoryInfoBase$instance;

export interface DirectoryInfoWrapper$instance extends DirectoryInfoBase {
    readonly fullName: string;
    readonly name: string;
    readonly parentDirectory: DirectoryInfoBase | undefined;
    enumerateFileSystemInfos(): IEnumerable<FileSystemInfoBase>;
    getDirectory(name: string): DirectoryInfoBase | undefined;
    getFile(name: string): FileInfoBase;
}


export const DirectoryInfoWrapper: {
    new(directoryInfo: DirectoryInfo): DirectoryInfoWrapper;
};


export type DirectoryInfoWrapper = DirectoryInfoWrapper$instance;

export interface FileInfoBase$instance extends FileSystemInfoBase {
}


export const FileInfoBase: {
};


export type FileInfoBase = FileInfoBase$instance;

export interface FileInfoWrapper$instance extends FileInfoBase {
    readonly fullName: string;
    readonly name: string;
    readonly parentDirectory: DirectoryInfoBase | undefined;
}


export const FileInfoWrapper: {
    new(fileInfo: FileInfo): FileInfoWrapper;
};


export type FileInfoWrapper = FileInfoWrapper$instance;

export interface FileSystemInfoBase$instance {
    readonly fullName: string;
    readonly name: string;
    readonly parentDirectory: DirectoryInfoBase | undefined;
}


export const FileSystemInfoBase: {
};


export type FileSystemInfoBase = FileSystemInfoBase$instance;

