// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Primitives
// Assembly: Microsoft.Extensions.Primitives

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ICollection_1, IComparer_1, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerable, IEnumerator } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action, Action_1, Boolean as ClrBoolean, Char, Func_1, IDisposable, IEquatable_1, Int32, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, String as ClrString, StringComparison, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IChangeToken$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Primitives_IChangeToken: never;

    readonly HasChanged: boolean;
    readonly ActiveChangeCallbacks: boolean;
    RegisterChangeCallback(callback: Action_1<JsValue | null>, state: JsValue | null): IDisposable;
}


export type IChangeToken = IChangeToken$instance;

export interface InplaceStringBuilder$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_InplaceStringBuilder: never;

    Capacity: int;
    Append(value: string | null): void;
    Append(segment: StringSegment): void;
    Append(value: string | null, offset: int, count: int): void;
    Append(c: char): void;
    ToString(): string | null;
}


export const InplaceStringBuilder: {
    new(capacity: int): InplaceStringBuilder;
};


export type InplaceStringBuilder = InplaceStringBuilder$instance;

export interface StringSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringSegment: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Buffer: string | null;
    readonly HasValue: boolean;
    readonly Length: int;
    readonly Offset: int;
    readonly Value: string | null;
    AsMemory(): ReadOnlyMemory_1<System_Internal.Char>;
    AsSpan(): ReadOnlySpan_1<System_Internal.Char>;
    AsSpan(start: int): ReadOnlySpan_1<System_Internal.Char>;
    AsSpan(start: int, length: int): ReadOnlySpan_1<System_Internal.Char>;
    EndsWith(text: string, comparisonType: StringComparison): boolean;
    Equals(obj: JsValue | null): boolean;
    Equals(other: StringSegment): boolean;
    Equals(other: StringSegment, comparisonType: StringComparison): boolean;
    Equals(text: string | null): boolean;
    Equals(text: string | null, comparisonType: StringComparison): boolean;
    GetHashCode(): int;
    IndexOf(c: char, start: int, count: int): int;
    IndexOf(c: char, start: int): int;
    IndexOf(c: char): int;
    IndexOfAny(anyOf: char[], startIndex: int, count: int): int;
    IndexOfAny(anyOf: char[], startIndex: int): int;
    IndexOfAny(anyOf: char[]): int;
    LastIndexOf(value: char): int;
    Split(chars: char[]): StringTokenizer;
    StartsWith(text: string, comparisonType: StringComparison): boolean;
    Subsegment(offset: int): StringSegment;
    Subsegment(offset: int, length: int): StringSegment;
    Substring(offset: int): string;
    Substring(offset: int, length: int): string;
    ToString(): string;
    Trim(): StringSegment;
    TrimEnd(): StringSegment;
    TrimStart(): StringSegment;
}


export const StringSegment: {
    new(buffer: string | null): StringSegment;
    new(buffer: string, offset: int, length: int): StringSegment;
    readonly Empty: StringSegment;
    Compare(a: StringSegment, b: StringSegment, comparisonType: StringComparison): int;
    Equals(a: StringSegment, b: StringSegment, comparisonType: StringComparison): boolean;
    IsNullOrEmpty(value: StringSegment): boolean;
};


export type StringSegment = StringSegment$instance & { readonly [index: number]: char; };

export interface StringTokenizer$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringTokenizer: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    GetEnumerator(): StringTokenizer_Enumerator;
}


export const StringTokenizer: {
    new(value: string, separators: char[]): StringTokenizer;
    new(value: StringSegment, separators: char[]): StringTokenizer;
};


export type StringTokenizer = StringTokenizer$instance;

export interface StringTokenizer_Enumerator$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringTokenizer_Enumerator: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Current: StringSegment;
    Dispose(): void;
    MoveNext(): boolean;
    Reset(): void;
}


export const StringTokenizer_Enumerator: {
    new(tokenizer: StringTokenizer): StringTokenizer_Enumerator;
};


export type StringTokenizer_Enumerator = StringTokenizer_Enumerator$instance;

export interface StringValues$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringValues: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IList_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Count: int;
    Equals(other: StringValues): boolean;
    Equals(other: string | null): boolean;
    Equals(other: (string | null)[] | null): boolean;
    Equals(obj: JsValue | null): boolean;
    GetEnumerator(): StringValues_Enumerator;
    GetHashCode(): int;
    ToArray(): (string | null)[];
    ToString(): string;
}


export const StringValues: {
    new(value: string | null): StringValues;
    new(values: (string | null)[] | null): StringValues;
    readonly Empty: StringValues;
    Concat(values1: StringValues, values2: StringValues): StringValues;
    Concat(values: StringValues, value: string | null): StringValues;
    Concat(value: string | null, values: StringValues): StringValues;
    Equals(left: StringValues, right: StringValues): boolean;
    Equals(left: StringValues, right: string | null): boolean;
    Equals(left: StringValues, right: (string | null)[] | null): boolean;
    Equals(left: string | null, right: StringValues): boolean;
    Equals(left: (string | null)[] | null, right: StringValues): boolean;
    IsNullOrEmpty(value: StringValues): boolean;
};


export type StringValues = StringValues$instance & { readonly [index: number]: string | null; };

export interface StringValues_Enumerator$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringValues_Enumerator: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Current: string | null;
    Dispose(): void;
    MoveNext(): boolean;
}


export const StringValues_Enumerator: {
    new(values: StringValues): StringValues_Enumerator;
};


export type StringValues_Enumerator = StringValues_Enumerator$instance;

export interface CancellationChangeToken$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_CancellationChangeToken: never;

    readonly __tsonic_iface_Microsoft_Extensions_Primitives_IChangeToken: never;

    ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
    RegisterChangeCallback(callback: Action_1<JsValue | null>, state: JsValue | null): IDisposable;
}


export const CancellationChangeToken: {
    new(cancellationToken: CancellationToken): CancellationChangeToken;
};


export interface __CancellationChangeToken$views {
    As_IChangeToken(): IChangeToken$instance;
}

export type CancellationChangeToken = CancellationChangeToken$instance & __CancellationChangeToken$views;


export interface CompositeChangeToken$instance extends IChangeToken$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_CompositeChangeToken: never;

    readonly __tsonic_iface_Microsoft_Extensions_Primitives_IChangeToken: never;

    readonly ActiveChangeCallbacks: boolean;
    readonly ChangeTokens: IReadOnlyList_1<IChangeToken>;
    readonly HasChanged: boolean;
    RegisterChangeCallback(callback: Action_1<JsValue | null>, state: JsValue | null): IDisposable;
}


export const CompositeChangeToken: {
    new(changeTokens: IReadOnlyList_1<IChangeToken>): CompositeChangeToken;
};


export interface __CompositeChangeToken$views {
    As_IChangeToken(): IChangeToken$instance;
}

export type CompositeChangeToken = CompositeChangeToken$instance & __CompositeChangeToken$views;


export interface StringSegmentComparer$instance {
    readonly __tsonic_type_Microsoft_Extensions_Primitives_StringSegmentComparer: never;

    readonly __tsonic_iface_System_Collections_Generic_IComparer_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;

    Compare(x: StringSegment, y: StringSegment): int;
    Equals(x: StringSegment, y: StringSegment): boolean;
    GetHashCode(obj: StringSegment): int;
}


export const StringSegmentComparer: {
    readonly Ordinal: StringSegmentComparer;
    readonly OrdinalIgnoreCase: StringSegmentComparer;
};


export type StringSegmentComparer = StringSegmentComparer$instance;

export abstract class ChangeToken$instance {
    static OnChange<TState>(changeTokenProducer: Func_1<IChangeToken | null>, changeTokenConsumer: Action_1<TState>, state: TState): IDisposable;
    static OnChange(changeTokenProducer: Func_1<IChangeToken | null>, changeTokenConsumer: Action): IDisposable;
}


export type ChangeToken = ChangeToken$instance;

export abstract class Extensions$instance {
    static Append(builder: StringBuilder, segment: StringSegment): StringBuilder;
}


export type Extensions = Extensions$instance;

