// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Logging
// Assembly: Microsoft.Extensions.Logging, Microsoft.Extensions.Logging.Abstractions, Microsoft.Extensions.Logging.Configuration, Microsoft.Extensions.Logging.Console, Microsoft.Extensions.Logging.Debug, Microsoft.Extensions.Logging.EventLog, Microsoft.Extensions.Logging.EventSource, Microsoft.Extensions.Logging.TraceSource

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IConfiguration } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { IServiceCollection } from "../../Microsoft.Extensions.DependencyInjection/internal/index.js";
import type { ConsoleFormatter, ConsoleFormatterOptions, ConsoleLoggerOptions, IConsoleLoggerSettings, JsonConsoleFormatterOptions, SimpleConsoleFormatterOptions } from "../../Microsoft.Extensions.Logging.Console/internal/index.js";
import type { EventLogSettings } from "../../Microsoft.Extensions.Logging.EventLog/internal/index.js";
import type { IOptions_1, IOptionsMonitor_1 } from "../../Microsoft.Extensions.Options/internal/index.js";
import type { IEnumerable, IList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { SourceSwitch, TraceListener } from "@tsonic/dotnet/System.Diagnostics.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Attribute, Boolean as ClrBoolean, Enum, Exception, Func, IComparable, IConvertible, IDisposable, IEquatable, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System.js";

export enum ActivityTrackingOptions {
    None = 0,
    SpanId = 1,
    TraceId = 2,
    ParentId = 4,
    TraceState = 8,
    TraceFlags = 16,
    Tags = 32,
    Baggage = 64
}


export enum LogLevel {
    Trace = 0,
    Debug = 1,
    Information = 2,
    Warning = 3,
    Error = 4,
    Critical = 5,
    None = 6
}


export interface IExternalScopeProvider$instance {
    ForEachScope<TState>(callback: Action<unknown, TState>, state: TState): void;
    Push(state: unknown): IDisposable;
}


export type IExternalScopeProvider = IExternalScopeProvider$instance;

export interface ILogger$instance {
    BeginScope<TState>(state: TState): IDisposable;
    IsEnabled(logLevel: LogLevel): boolean;
    Log<TState>(logLevel: LogLevel, eventId: EventId, state: TState, exception: Exception, formatter: Func<TState, Exception, System_Internal.String>): void;
}


export type ILogger = ILogger$instance;

export interface ILogger_1$instance<TCategoryName> extends ILogger {
    BeginScope<TState>(state: TState): IDisposable;
    IsEnabled(logLevel: LogLevel): boolean;
    Log<TState>(logLevel: LogLevel, eventId: EventId, state: TState, exception: Exception, formatter: Func<TState, Exception, System_Internal.String>): void;
}


export interface ILogger_1$instance<TCategoryName> extends ILogger$instance {}

export type ILogger_1<TCategoryName> = ILogger_1$instance<TCategoryName>;

export interface ILoggerFactory$instance extends IDisposable {
    AddProvider(provider: ILoggerProvider): void;
    CreateLogger(categoryName: string): ILogger;
}


export type ILoggerFactory = ILoggerFactory$instance;

export interface ILoggerProvider$instance extends IDisposable {
    CreateLogger(categoryName: string): ILogger;
}


export type ILoggerProvider = ILoggerProvider$instance;

export interface ILoggingBuilder$instance {
    readonly Services: IServiceCollection;
}


export type ILoggingBuilder = ILoggingBuilder$instance;

export interface ISupportExternalScope$instance {
    SetScopeProvider(scopeProvider: IExternalScopeProvider): void;
}


export type ISupportExternalScope = ISupportExternalScope$instance;

export interface EventId$instance {
    readonly Id: int;
    readonly Name: string;
    Equals(other: EventId): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const EventId: {
    new(id: int, name: string): EventId;
};


export type EventId = EventId$instance;

export interface LogDefineOptions$instance {
    SkipEnabledCheck: boolean;
}


export const LogDefineOptions: {
    new(): LogDefineOptions;
};


export type LogDefineOptions = LogDefineOptions$instance;

export interface Logger_1$instance<T> {
}


export const Logger_1: {
    new<T>(factory: ILoggerFactory): Logger_1<T>;
};


export interface __Logger_1$views<T> {
    As_ILogger(): ILogger$instance;
}

export interface Logger_1$instance<T> extends ILogger_1$instance<T> {}

export type Logger_1<T> = Logger_1$instance<T> & __Logger_1$views<T>;


export interface LoggerExternalScopeProvider$instance {
    ForEachScope<TState>(callback: Action<unknown, TState>, state: TState): void;
    Push(state: unknown): IDisposable;
}


export const LoggerExternalScopeProvider: {
    new(): LoggerExternalScopeProvider;
};


export interface __LoggerExternalScopeProvider$views {
    As_IExternalScopeProvider(): IExternalScopeProvider$instance;
}

export interface LoggerExternalScopeProvider$instance extends IExternalScopeProvider$instance {}

export type LoggerExternalScopeProvider = LoggerExternalScopeProvider$instance & __LoggerExternalScopeProvider$views;


export interface LoggerFactory$instance {
    AddProvider(provider: ILoggerProvider): void;
    CreateLogger(categoryName: string): ILogger;
    Dispose(): void;
}


export const LoggerFactory: {
    new(): LoggerFactory;
    new(providers: IEnumerable<ILoggerProvider>): LoggerFactory;
    new(providers: IEnumerable<ILoggerProvider>, filterOptions: LoggerFilterOptions): LoggerFactory;
    new(providers: IEnumerable<ILoggerProvider>, filterOption: IOptionsMonitor_1<LoggerFilterOptions>): LoggerFactory;
    new(providers: IEnumerable<ILoggerProvider>, filterOption: IOptionsMonitor_1<LoggerFilterOptions>, options: IOptions_1<LoggerFactoryOptions>): LoggerFactory;
    new(providers: IEnumerable<ILoggerProvider>, filterOption: IOptionsMonitor_1<LoggerFilterOptions>, options: IOptions_1<LoggerFactoryOptions>, scopeProvider: IExternalScopeProvider): LoggerFactory;
    Create(configure: Action<ILoggingBuilder>): ILoggerFactory;
};


export interface __LoggerFactory$views {
    As_ILoggerFactory(): ILoggerFactory$instance;
}

export interface LoggerFactory$instance extends ILoggerFactory$instance {}

export type LoggerFactory = LoggerFactory$instance & __LoggerFactory$views;


export interface LoggerFactoryOptions$instance {
    ActivityTrackingOptions: ActivityTrackingOptions;
}


export const LoggerFactoryOptions: {
    new(): LoggerFactoryOptions;
};


export type LoggerFactoryOptions = LoggerFactoryOptions$instance;

export interface LoggerFilterOptions$instance {
    CaptureScopes: boolean;
    MinLevel: LogLevel;
    readonly Rules: IList<LoggerFilterRule>;
}


export const LoggerFilterOptions: {
    new(): LoggerFilterOptions;
};


export type LoggerFilterOptions = LoggerFilterOptions$instance;

export interface LoggerFilterRule$instance {
    readonly CategoryName: string | undefined;
    readonly Filter: Func<string | undefined, string | undefined, LogLevel, System_Internal.Boolean> | undefined;
    readonly LogLevel: Nullable<LogLevel>;
    readonly ProviderName: string | undefined;
    ToString(): string;
}


export const LoggerFilterRule: {
    new(providerName: string, categoryName: string, logLevel: Nullable<LogLevel>, filter: Func<System_Internal.String, System_Internal.String, LogLevel, System_Internal.Boolean>): LoggerFilterRule;
};


export type LoggerFilterRule = LoggerFilterRule$instance;

export interface LoggerMessageAttribute$instance extends Attribute {
    EventId: int;
    get EventName(): string | undefined;
    set EventName(value: string);
    Level: LogLevel;
    Message: string;
    SkipEnabledCheck: boolean;
}


export const LoggerMessageAttribute: {
    new(): LoggerMessageAttribute;
    new(eventId: int, level: LogLevel, message: string): LoggerMessageAttribute;
    new(level: LogLevel, message: string): LoggerMessageAttribute;
    new(level: LogLevel): LoggerMessageAttribute;
    new(message: string): LoggerMessageAttribute;
};


export type LoggerMessageAttribute = LoggerMessageAttribute$instance;

export interface ProviderAliasAttribute$instance extends Attribute {
    readonly Alias: string;
}


export const ProviderAliasAttribute: {
    new(alias: string): ProviderAliasAttribute;
};


export type ProviderAliasAttribute = ProviderAliasAttribute$instance;

export abstract class ConsoleLoggerExtensions$instance {
    static AddConsole(factory: ILoggerFactory, configuration: IConfiguration): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, settings: IConsoleLoggerSettings): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, minLevel: LogLevel, includeScopes: boolean): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, minLevel: LogLevel): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, includeScopes: boolean): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, filter: Func<System_Internal.String, LogLevel, System_Internal.Boolean>, includeScopes: boolean): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory, filter: Func<System_Internal.String, LogLevel, System_Internal.Boolean>): ILoggerFactory;
    static AddConsole(factory: ILoggerFactory): ILoggerFactory;
    static AddConsole(builder: ILoggingBuilder, configure: Action<ConsoleLoggerOptions>): ILoggingBuilder;
    static AddConsole(builder: ILoggingBuilder): ILoggingBuilder;
    static AddConsoleFormatter<TFormatter extends ConsoleFormatter, TOptions extends ConsoleFormatterOptions>(builder: ILoggingBuilder, configure: Action<TOptions>): ILoggingBuilder;
    static AddConsoleFormatter<TFormatter extends ConsoleFormatter, TOptions extends ConsoleFormatterOptions>(builder: ILoggingBuilder): ILoggingBuilder;
    static AddJsonConsole(builder: ILoggingBuilder, configure: Action<JsonConsoleFormatterOptions>): ILoggingBuilder;
    static AddJsonConsole(builder: ILoggingBuilder): ILoggingBuilder;
    static AddSimpleConsole(builder: ILoggingBuilder, configure: Action<SimpleConsoleFormatterOptions>): ILoggingBuilder;
    static AddSimpleConsole(builder: ILoggingBuilder): ILoggingBuilder;
    static AddSystemdConsole(builder: ILoggingBuilder, configure: Action<ConsoleFormatterOptions>): ILoggingBuilder;
    static AddSystemdConsole(builder: ILoggingBuilder): ILoggingBuilder;
}


export type ConsoleLoggerExtensions = ConsoleLoggerExtensions$instance;

export abstract class DebugLoggerFactoryExtensions$instance {
    static AddDebug(factory: ILoggerFactory, minLevel: LogLevel): ILoggerFactory;
    static AddDebug(factory: ILoggerFactory, filter: Func<System_Internal.String, LogLevel, System_Internal.Boolean>): ILoggerFactory;
    static AddDebug(factory: ILoggerFactory): ILoggerFactory;
    static AddDebug(builder: ILoggingBuilder): ILoggingBuilder;
}


export type DebugLoggerFactoryExtensions = DebugLoggerFactoryExtensions$instance;

export abstract class EventLoggerFactoryExtensions$instance {
    static AddEventLog(factory: ILoggerFactory, settings: EventLogSettings): ILoggerFactory;
    static AddEventLog(factory: ILoggerFactory, minLevel: LogLevel): ILoggerFactory;
    static AddEventLog(factory: ILoggerFactory): ILoggerFactory;
    static AddEventLog(builder: ILoggingBuilder, settings: EventLogSettings): ILoggingBuilder;
    static AddEventLog(builder: ILoggingBuilder, configure: Action<EventLogSettings>): ILoggingBuilder;
    static AddEventLog(builder: ILoggingBuilder): ILoggingBuilder;
}


export type EventLoggerFactoryExtensions = EventLoggerFactoryExtensions$instance;

export abstract class EventSourceLoggerFactoryExtensions$instance {
    static AddEventSourceLogger(factory: ILoggerFactory): ILoggerFactory;
    static AddEventSourceLogger(builder: ILoggingBuilder): ILoggingBuilder;
}


export type EventSourceLoggerFactoryExtensions = EventSourceLoggerFactoryExtensions$instance;

export abstract class FilterLoggingBuilderExtensions$instance {
    static AddFilter(builder: ILoggingBuilder, levelFilter: Func<LogLevel, System_Internal.Boolean>): ILoggingBuilder;
    static AddFilter(builder: ILoggingBuilder, categoryLevelFilter: Func<System_Internal.String, LogLevel, System_Internal.Boolean>): ILoggingBuilder;
    static AddFilter(builder: ILoggingBuilder, filter: Func<System_Internal.String, System_Internal.String, LogLevel, System_Internal.Boolean>): ILoggingBuilder;
    static AddFilter(builder: ILoggingBuilder, category: string, level: LogLevel): ILoggingBuilder;
    static AddFilter(builder: ILoggingBuilder, category: string, levelFilter: Func<LogLevel, System_Internal.Boolean>): ILoggingBuilder;
    static AddFilter(builder: LoggerFilterOptions, levelFilter: Func<LogLevel, System_Internal.Boolean>): LoggerFilterOptions;
    static AddFilter(builder: LoggerFilterOptions, categoryLevelFilter: Func<System_Internal.String, LogLevel, System_Internal.Boolean>): LoggerFilterOptions;
    static AddFilter(builder: LoggerFilterOptions, filter: Func<System_Internal.String, System_Internal.String, LogLevel, System_Internal.Boolean>): LoggerFilterOptions;
    static AddFilter(builder: LoggerFilterOptions, category: string, level: LogLevel): LoggerFilterOptions;
    static AddFilter(builder: LoggerFilterOptions, category: string, levelFilter: Func<LogLevel, System_Internal.Boolean>): LoggerFilterOptions;
}


export type FilterLoggingBuilderExtensions = FilterLoggingBuilderExtensions$instance;

export abstract class LoggerExtensions$instance {
    static BeginScope(logger: ILogger, messageFormat: string, ...args: unknown[]): IDisposable | undefined;
    static Log(logger: ILogger, logLevel: LogLevel, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static Log(logger: ILogger, logLevel: LogLevel, eventId: EventId, message: string, ...args: unknown[]): void;
    static Log(logger: ILogger, logLevel: LogLevel, exception: Exception, message: string, ...args: unknown[]): void;
    static Log(logger: ILogger, logLevel: LogLevel, message: string, ...args: unknown[]): void;
    static LogCritical(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogCritical(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogCritical(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogCritical(logger: ILogger, message: string, ...args: unknown[]): void;
    static LogDebug(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogDebug(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogDebug(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogDebug(logger: ILogger, message: string, ...args: unknown[]): void;
    static LogError(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogError(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogError(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogError(logger: ILogger, message: string, ...args: unknown[]): void;
    static LogInformation(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogInformation(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogInformation(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogInformation(logger: ILogger, message: string, ...args: unknown[]): void;
    static LogTrace(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogTrace(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogTrace(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogTrace(logger: ILogger, message: string, ...args: unknown[]): void;
    static LogWarning(logger: ILogger, eventId: EventId, exception: Exception, message: string, ...args: unknown[]): void;
    static LogWarning(logger: ILogger, eventId: EventId, message: string, ...args: unknown[]): void;
    static LogWarning(logger: ILogger, exception: Exception, message: string, ...args: unknown[]): void;
    static LogWarning(logger: ILogger, message: string, ...args: unknown[]): void;
}


export type LoggerExtensions = LoggerExtensions$instance;

export abstract class LoggerFactoryExtensions$instance {
    static CreateLogger(factory: ILoggerFactory, type: Type): ILogger;
    static CreateLogger<T>(factory: ILoggerFactory): ILogger_1<T>;
}


export type LoggerFactoryExtensions = LoggerFactoryExtensions$instance;

export abstract class LoggerMessage$instance {
    static Define<T1>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, Exception | undefined>;
    static Define<T1, T2>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, T2, Exception | undefined>;
    static Define<T1, T2, T3>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, T2, T3, Exception | undefined>;
    static Define<T1, T2, T3, T4>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, T2, T3, T4, Exception | undefined>;
    static Define<T1, T2, T3, T4, T5>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, T2, T3, T4, T5, Exception | undefined>;
    static Define<T1, T2, T3, T4, T5, T6>(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, T1, T2, T3, T4, T5, T6, Exception | undefined>;
    static Define(logLevel: LogLevel, eventId: EventId, formatString: string, options: LogDefineOptions): Action<ILogger, Exception | undefined>;
    static Define<T1>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, Exception | undefined>;
    static Define<T1, T2>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, T2, Exception | undefined>;
    static Define<T1, T2, T3>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, T2, T3, Exception | undefined>;
    static Define<T1, T2, T3, T4>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, T2, T3, T4, Exception | undefined>;
    static Define<T1, T2, T3, T4, T5>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, T2, T3, T4, T5, Exception | undefined>;
    static Define<T1, T2, T3, T4, T5, T6>(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, T1, T2, T3, T4, T5, T6, Exception | undefined>;
    static Define(logLevel: LogLevel, eventId: EventId, formatString: string): Action<ILogger, Exception | undefined>;
    static DefineScope<T1>(formatString: string): Func<ILogger, T1, IDisposable | undefined>;
    static DefineScope<T1, T2>(formatString: string): Func<ILogger, T1, T2, IDisposable | undefined>;
    static DefineScope<T1, T2, T3>(formatString: string): Func<ILogger, T1, T2, T3, IDisposable | undefined>;
    static DefineScope<T1, T2, T3, T4>(formatString: string): Func<ILogger, T1, T2, T3, T4, IDisposable | undefined>;
    static DefineScope<T1, T2, T3, T4, T5>(formatString: string): Func<ILogger, T1, T2, T3, T4, T5, IDisposable | undefined>;
    static DefineScope<T1, T2, T3, T4, T5, T6>(formatString: string): Func<ILogger, T1, T2, T3, T4, T5, T6, IDisposable | undefined>;
    static DefineScope(formatString: string): Func<ILogger, IDisposable | undefined>;
}


export type LoggerMessage = LoggerMessage$instance;

export abstract class LoggingBuilderExtensions$instance {
    static AddProvider(builder: ILoggingBuilder, provider: ILoggerProvider): ILoggingBuilder;
    static ClearProviders(builder: ILoggingBuilder): ILoggingBuilder;
    static Configure(builder: ILoggingBuilder, action: Action<LoggerFactoryOptions>): ILoggingBuilder;
    static SetMinimumLevel(builder: ILoggingBuilder, level: LogLevel): ILoggingBuilder;
}


export type LoggingBuilderExtensions = LoggingBuilderExtensions$instance;

export abstract class LoggingBuilderExtensions2$instance {
    static AddConfiguration(builder: ILoggingBuilder, configuration: IConfiguration): ILoggingBuilder;
}


export type LoggingBuilderExtensions2 = LoggingBuilderExtensions2$instance;

export abstract class TraceSourceFactoryExtensions$instance {
    static AddTraceSource(factory: ILoggerFactory, sourceSwitch: SourceSwitch, listener: TraceListener): ILoggerFactory;
    static AddTraceSource(factory: ILoggerFactory, sourceSwitch: SourceSwitch): ILoggerFactory;
    static AddTraceSource(factory: ILoggerFactory, switchName: string, listener: TraceListener): ILoggerFactory;
    static AddTraceSource(factory: ILoggerFactory, switchName: string): ILoggerFactory;
    static AddTraceSource(builder: ILoggingBuilder, sourceSwitch: SourceSwitch, listener: TraceListener): ILoggingBuilder;
    static AddTraceSource(builder: ILoggingBuilder, sourceSwitch: SourceSwitch): ILoggingBuilder;
    static AddTraceSource(builder: ILoggingBuilder, switchName: string, listener: TraceListener): ILoggingBuilder;
    static AddTraceSource(builder: ILoggingBuilder, switchName: string): ILoggingBuilder;
}


export type TraceSourceFactoryExtensions = TraceSourceFactoryExtensions$instance;

