// Generated by tsbindgen - Architecture
// Namespace: System.Diagnostics.Eventing.Reader
// Assembly: System.Diagnostics.EventLog

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable_1, IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { CultureInfo } from "@tsonic/dotnet/System.Globalization/internal/index.js";
import type { SeekOrigin } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { SecurityIdentifier } from "@tsonic/dotnet/System.Security.Principal/internal/index.js";
import type { SecureString } from "@tsonic/dotnet/System.Security/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, DateTime, Enum, EventArgs, EventHandler_1, Exception, Guid, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Uri, Void } from "@tsonic/dotnet/System/internal/index.js";

export enum EventLogIsolation {
    Application = 0,
    System = 1,
    Custom = 2
}


export enum EventLogMode {
    Circular = 0,
    AutoBackup = 1,
    Retain = 2
}


export enum EventLogType {
    Administrative = 0,
    Operational = 1,
    Analytical = 2,
    Debug = 3
}


export enum PathType {
    LogName = 1,
    FilePath = 2
}


export enum SessionAuthentication {
    Default = 0,
    Negotiate = 1,
    Kerberos = 2,
    Ntlm = 3
}


export enum StandardEventKeywords {
    None = 0,
    ResponseTime = 281474976710656,
    WdiContext = 562949953421312,
    WdiDiagnostic = 1125899906842624,
    Sqm = 2251799813685248,
    AuditFailure = 4503599627370496,
    CorrelationHint = 4503599627370496,
    AuditSuccess = 9007199254740992,
    CorrelationHint2 = 18014398509481984,
    EventLogClassic = 36028797018963968
}


export enum StandardEventLevel {
    LogAlways = 0,
    Critical = 1,
    Error = 2,
    Warning = 3,
    Informational = 4,
    Verbose = 5
}


export enum StandardEventOpcode {
    Info = 0,
    Start = 1,
    Stop = 2,
    DataCollectionStart = 3,
    DataCollectionStop = 4,
    Extension = 5,
    Reply = 6,
    Resume = 7,
    Suspend = 8,
    Send = 9,
    Receive = 240
}


export enum StandardEventTask {
    None = 0
}


export interface EventBookmark$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventBookmark: never;

    readonly BookmarkXml: string;
}


export const EventBookmark: {
    new(bookmarkXml: string): EventBookmark;
};


export type EventBookmark = EventBookmark$instance;

export interface EventKeyword$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventKeyword: never;

    readonly DisplayName: string;
    readonly Name: string;
    readonly Value: long;
}


export const EventKeyword: {
};


export type EventKeyword = EventKeyword$instance;

export interface EventLevel$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLevel: never;

    readonly DisplayName: string;
    readonly Name: string;
    readonly Value: int;
}


export const EventLevel: {
};


export type EventLevel = EventLevel$instance;

export interface EventLogConfiguration$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogConfiguration: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly IsClassicLog: boolean;
    IsEnabled: boolean;
    LogFilePath: string;
    readonly LogIsolation: EventLogIsolation;
    LogMode: EventLogMode;
    readonly LogName: string;
    readonly LogType: EventLogType;
    MaximumSizeInBytes: long;
    readonly OwningProviderName: string;
    readonly ProviderBufferSize: Nullable_1<System_Internal.Int32>;
    readonly ProviderControlGuid: Nullable_1<Guid>;
    get ProviderKeywords(): Nullable_1<System_Internal.Int64>;
    set ProviderKeywords(value: Nullable_1<System_Internal.Int64> | long);
    readonly ProviderLatency: Nullable_1<System_Internal.Int32>;
    get ProviderLevel(): Nullable_1<System_Internal.Int32>;
    set ProviderLevel(value: Nullable_1<System_Internal.Int32> | int);
    readonly ProviderMaximumNumberOfBuffers: Nullable_1<System_Internal.Int32>;
    readonly ProviderMinimumNumberOfBuffers: Nullable_1<System_Internal.Int32>;
    readonly ProviderNames: IEnumerable_1<System_Internal.String>;
    SecurityDescriptor: string;
    Dispose(): void;
    Dispose(disposing: boolean): void;
    SaveChanges(): void;
}


export const EventLogConfiguration: {
    new(logName: string): EventLogConfiguration;
    new(logName: string, session: EventLogSession): EventLogConfiguration;
};


export type EventLogConfiguration = EventLogConfiguration$instance;

export interface EventLogException$instance extends Exception {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly Message: string;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export const EventLogException: {
    new(): EventLogException;
    new(message: string): EventLogException;
    new(message: string, innerException: Exception): EventLogException;
};


export type EventLogException = EventLogException$instance;

export interface EventLogInformation$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogInformation: never;

    readonly Attributes: Nullable_1<System_Internal.Int32>;
    readonly CreationTime: Nullable_1<DateTime>;
    readonly FileSize: Nullable_1<System_Internal.Int64>;
    readonly IsLogFull: Nullable_1<System_Internal.Boolean>;
    readonly LastAccessTime: Nullable_1<DateTime>;
    readonly LastWriteTime: Nullable_1<DateTime>;
    readonly OldestRecordNumber: Nullable_1<System_Internal.Int64>;
    readonly RecordCount: Nullable_1<System_Internal.Int64>;
}


export const EventLogInformation: {
};


export type EventLogInformation = EventLogInformation$instance;

export interface EventLogInvalidDataException$instance extends EventLogException {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogInvalidDataException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const EventLogInvalidDataException: {
    new(): EventLogInvalidDataException;
    new(message: string): EventLogInvalidDataException;
    new(message: string, innerException: Exception): EventLogInvalidDataException;
};


export type EventLogInvalidDataException = EventLogInvalidDataException$instance;

export interface EventLogLink$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogLink: never;

    readonly DisplayName: string;
    readonly IsImported: boolean;
    readonly LogName: string;
}


export const EventLogLink: {
};


export type EventLogLink = EventLogLink$instance;

export interface EventLogNotFoundException$instance extends EventLogException {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogNotFoundException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const EventLogNotFoundException: {
    new(): EventLogNotFoundException;
    new(message: string): EventLogNotFoundException;
    new(message: string, innerException: Exception): EventLogNotFoundException;
};


export type EventLogNotFoundException = EventLogNotFoundException$instance;

export interface EventLogPropertySelector$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogPropertySelector: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Dispose(): void;
    Dispose(disposing: boolean): void;
}


export const EventLogPropertySelector: {
    new(propertyQueries: IEnumerable_1<System_Internal.String>): EventLogPropertySelector;
};


export type EventLogPropertySelector = EventLogPropertySelector$instance;

export interface EventLogProviderDisabledException$instance extends EventLogException {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogProviderDisabledException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const EventLogProviderDisabledException: {
    new(): EventLogProviderDisabledException;
    new(message: string): EventLogProviderDisabledException;
    new(message: string, innerException: Exception): EventLogProviderDisabledException;
};


export type EventLogProviderDisabledException = EventLogProviderDisabledException$instance;

export interface EventLogQuery$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogQuery: never;

    ReverseDirection: boolean;
    Session: EventLogSession;
    TolerateQueryErrors: boolean;
}


export const EventLogQuery: {
    new(path: string, pathType: PathType): EventLogQuery;
    new(path: string, pathType: PathType, query: string): EventLogQuery;
};


export type EventLogQuery = EventLogQuery$instance;

export interface EventLogReader$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogReader: never;

    readonly __tsonic_iface_System_IDisposable: never;

    BatchSize: int;
    readonly LogStatus: IList_1<EventLogStatus>;
    CancelReading(): void;
    Dispose(): void;
    Dispose(disposing: boolean): void;
    ReadEvent(): EventRecord;
    ReadEvent(timeout: TimeSpan): EventRecord;
    Seek(bookmark: EventBookmark): void;
    Seek(bookmark: EventBookmark, offset: long): void;
    Seek(origin: SeekOrigin, offset: long): void;
}


export const EventLogReader: {
    new(eventQuery: EventLogQuery): EventLogReader;
    new(eventQuery: EventLogQuery, bookmark: EventBookmark): EventLogReader;
    new(path: string): EventLogReader;
    new(path: string, pathType: PathType): EventLogReader;
};


export type EventLogReader = EventLogReader$instance;

export interface EventLogReadingException$instance extends EventLogException {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogReadingException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const EventLogReadingException: {
    new(): EventLogReadingException;
    new(message: string): EventLogReadingException;
    new(message: string, innerException: Exception): EventLogReadingException;
};


export type EventLogReadingException = EventLogReadingException$instance;

export interface EventLogRecord$instance extends EventRecord {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogRecord: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly ActivityId: Nullable_1<Guid>;
    readonly Bookmark: EventBookmark;
    readonly ContainerLog: string;
    readonly Id: int;
    readonly Keywords: Nullable_1<System_Internal.Int64>;
    readonly KeywordsDisplayNames: IEnumerable_1<System_Internal.String>;
    readonly Level: Nullable_1<System_Internal.Byte>;
    readonly LevelDisplayName: string;
    readonly LogName: string;
    readonly MachineName: string;
    readonly MatchedQueryIds: IEnumerable_1<System_Internal.Int32>;
    readonly Opcode: Nullable_1<System_Internal.Int16>;
    readonly OpcodeDisplayName: string;
    readonly ProcessId: Nullable_1<System_Internal.Int32>;
    readonly Properties: IList_1<EventProperty>;
    readonly ProviderId: Nullable_1<Guid>;
    readonly ProviderName: string;
    readonly Qualifiers: Nullable_1<System_Internal.Int32>;
    readonly RecordId: Nullable_1<System_Internal.Int64>;
    readonly RelatedActivityId: Nullable_1<Guid>;
    readonly Task: Nullable_1<System_Internal.Int32>;
    readonly TaskDisplayName: string;
    readonly ThreadId: Nullable_1<System_Internal.Int32>;
    readonly TimeCreated: Nullable_1<DateTime>;
    readonly UserId: SecurityIdentifier;
    readonly Version: Nullable_1<System_Internal.Byte>;
    Dispose(disposing: boolean): void;
    Dispose(): void;
    FormatDescription(): string;
    FormatDescription(values: IEnumerable_1<unknown>): string;
    GetPropertyValues(propertySelector: EventLogPropertySelector): IList_1<unknown>;
    ToXml(): string;
}


export const EventLogRecord: {
};


export type EventLogRecord = EventLogRecord$instance;

export interface EventLogSession$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogSession: never;

    readonly __tsonic_iface_System_IDisposable: never;

    CancelCurrentOperations(): void;
    ClearLog(logName: string): void;
    ClearLog(logName: string, backupPath: string): void;
    Dispose(): void;
    Dispose(disposing: boolean): void;
    ExportLog(path: string, pathType: PathType, query: string, targetFilePath: string): void;
    ExportLog(path: string, pathType: PathType, query: string, targetFilePath: string, tolerateQueryErrors: boolean): void;
    ExportLogAndMessages(path: string, pathType: PathType, query: string, targetFilePath: string): void;
    ExportLogAndMessages(path: string, pathType: PathType, query: string, targetFilePath: string, tolerateQueryErrors: boolean, targetCultureInfo: CultureInfo): void;
    GetLogInformation(logName: string, pathType: PathType): EventLogInformation;
    GetLogNames(): IEnumerable_1<System_Internal.String>;
    GetProviderNames(): IEnumerable_1<System_Internal.String>;
}


export const EventLogSession: {
    new(): EventLogSession;
    new(server: string): EventLogSession;
    new(server: string, domain: string, user: string, password: SecureString, logOnType: SessionAuthentication): EventLogSession;
    readonly GlobalSession: EventLogSession;
};


export type EventLogSession = EventLogSession$instance;

export interface EventLogStatus$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogStatus: never;

    readonly LogName: string;
    readonly StatusCode: int;
}


export const EventLogStatus: {
};


export type EventLogStatus = EventLogStatus$instance;

export interface EventLogWatcher$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventLogWatcher: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Enabled: boolean;
    Dispose(): void;
    Dispose(disposing: boolean): void;
}


export const EventLogWatcher: {
    new(eventQuery: EventLogQuery): EventLogWatcher;
    new(eventQuery: EventLogQuery, bookmark: EventBookmark): EventLogWatcher;
    new(eventQuery: EventLogQuery, bookmark: EventBookmark, readExistingEvents: boolean): EventLogWatcher;
    new(path: string): EventLogWatcher;
};


export type EventLogWatcher = EventLogWatcher$instance;

export interface EventMetadata$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventMetadata: never;

    readonly Description: string;
    readonly Id: long;
    readonly Keywords: IEnumerable_1<EventKeyword>;
    readonly Level: EventLevel;
    readonly LogLink: EventLogLink;
    readonly Opcode: EventOpcode;
    readonly Task: EventTask;
    readonly Template: string;
    readonly Version: byte;
}


export const EventMetadata: {
};


export type EventMetadata = EventMetadata$instance;

export interface EventOpcode$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventOpcode: never;

    readonly DisplayName: string;
    readonly Name: string;
    readonly Value: int;
}


export const EventOpcode: {
};


export type EventOpcode = EventOpcode$instance;

export interface EventProperty$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventProperty: never;

    readonly Value: unknown;
}


export const EventProperty: {
};


export type EventProperty = EventProperty$instance;

export interface EventRecord$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventRecord: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly ActivityId: Nullable_1<Guid>;
    readonly Bookmark: EventBookmark;
    readonly Id: int;
    readonly Keywords: Nullable_1<System_Internal.Int64>;
    readonly KeywordsDisplayNames: IEnumerable_1<System_Internal.String>;
    readonly Level: Nullable_1<System_Internal.Byte>;
    readonly LevelDisplayName: string;
    readonly LogName: string;
    readonly MachineName: string;
    readonly Opcode: Nullable_1<System_Internal.Int16>;
    readonly OpcodeDisplayName: string;
    readonly ProcessId: Nullable_1<System_Internal.Int32>;
    readonly Properties: IList_1<EventProperty>;
    readonly ProviderId: Nullable_1<Guid>;
    readonly ProviderName: string;
    readonly Qualifiers: Nullable_1<System_Internal.Int32>;
    readonly RecordId: Nullable_1<System_Internal.Int64>;
    readonly RelatedActivityId: Nullable_1<Guid>;
    readonly Task: Nullable_1<System_Internal.Int32>;
    readonly TaskDisplayName: string;
    readonly ThreadId: Nullable_1<System_Internal.Int32>;
    readonly TimeCreated: Nullable_1<DateTime>;
    readonly UserId: SecurityIdentifier;
    readonly Version: Nullable_1<System_Internal.Byte>;
    Dispose(): void;
    Dispose(disposing: boolean): void;
    FormatDescription(): string;
    FormatDescription(values: IEnumerable_1<unknown>): string;
    ToXml(): string;
}


export const EventRecord: (abstract new() => EventRecord) & {
};


export type EventRecord = EventRecord$instance;

export interface EventRecordWrittenEventArgs$instance extends EventArgs {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventRecordWrittenEventArgs: never;

    readonly EventException: Exception;
    readonly EventRecord: EventRecord;
}


export const EventRecordWrittenEventArgs: {
};


export type EventRecordWrittenEventArgs = EventRecordWrittenEventArgs$instance;

export interface EventTask$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_EventTask: never;

    readonly DisplayName: string;
    readonly EventGuid: Guid;
    readonly Name: string;
    readonly Value: int;
}


export const EventTask: {
};


export type EventTask = EventTask$instance;

export interface ProviderMetadata$instance {
    readonly __tsonic_type_System_Diagnostics_Eventing_Reader_ProviderMetadata: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly DisplayName: string;
    readonly Events: IEnumerable_1<EventMetadata>;
    readonly HelpLink: Uri;
    readonly Id: Guid;
    readonly Keywords: IList_1<EventKeyword>;
    readonly Levels: IList_1<EventLevel>;
    readonly LogLinks: IList_1<EventLogLink>;
    readonly MessageFilePath: string;
    readonly Name: string;
    readonly Opcodes: IList_1<EventOpcode>;
    readonly ParameterFilePath: string;
    readonly ResourceFilePath: string;
    readonly Tasks: IList_1<EventTask>;
    Dispose(): void;
    Dispose(disposing: boolean): void;
}


export const ProviderMetadata: {
    new(providerName: string): ProviderMetadata;
    new(providerName: string, session: EventLogSession, targetCultureInfo: CultureInfo): ProviderMetadata;
};


export type ProviderMetadata = ProviderMetadata$instance;

