// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Extensions.Configuration.Ini
// Assembly: Microsoft.Extensions.Configuration.Ini

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_Extensions_Configuration_Internal from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { FileConfigurationProvider, FileConfigurationSource, FileLoadExceptionContext, IConfigurationBuilder, IConfigurationProvider, IConfigurationSource, StreamConfigurationProvider, StreamConfigurationSource } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { IFileProvider } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IDictionary_2, IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, IDisposable, Int32, String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IniConfigurationProvider$instance extends FileConfigurationProvider, System_Internal.IDisposable {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_Ini_IniConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Load(stream: Stream): void;
    Load(): void;
}


export const IniConfigurationProvider: {
    new(source: IniConfigurationSource): IniConfigurationProvider;
};


export interface __IniConfigurationProvider$views {
    As_IConfigurationProvider(): Microsoft_Extensions_Configuration_Internal.IConfigurationProvider$instance;
}

export type IniConfigurationProvider = IniConfigurationProvider$instance & __IniConfigurationProvider$views;


export interface IniConfigurationSource$instance extends FileConfigurationSource, Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_Ini_IniConfigurationSource: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const IniConfigurationSource: {
    new(): IniConfigurationSource;
};


export interface __IniConfigurationSource$views {
    As_IConfigurationSource(): Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance;
}

export type IniConfigurationSource = IniConfigurationSource$instance & __IniConfigurationSource$views;


export interface IniStreamConfigurationProvider$instance extends StreamConfigurationProvider {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_Ini_IniStreamConfigurationProvider: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationProvider: never;

    Load(stream: Stream): void;
    Load(): void;
}


export const IniStreamConfigurationProvider: {
    new(source: IniStreamConfigurationSource): IniStreamConfigurationProvider;
    Read(stream: Stream): IDictionary_2<System_Internal.String, string | null>;
};


export interface __IniStreamConfigurationProvider$views {
    As_IConfigurationProvider(): Microsoft_Extensions_Configuration_Internal.IConfigurationProvider$instance;
}

export type IniStreamConfigurationProvider = IniStreamConfigurationProvider$instance & __IniStreamConfigurationProvider$views;


export interface IniStreamConfigurationSource$instance extends StreamConfigurationSource, Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance {
    readonly __tsonic_type_Microsoft_Extensions_Configuration_Ini_IniStreamConfigurationSource: never;

    readonly __tsonic_iface_Microsoft_Extensions_Configuration_IConfigurationSource: never;

    Build(builder: IConfigurationBuilder): IConfigurationProvider;
}


export const IniStreamConfigurationSource: {
    new(): IniStreamConfigurationSource;
};


export interface __IniStreamConfigurationSource$views {
    As_IConfigurationSource(): Microsoft_Extensions_Configuration_Internal.IConfigurationSource$instance;
}

export type IniStreamConfigurationSource = IniStreamConfigurationSource$instance & __IniStreamConfigurationSource$views;
