// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments
// Assembly: Microsoft.Extensions.FileSystemGlobbing

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_Extensions_FileSystemGlobbing_Internal_Internal from "../../Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js";
import type { IPathSegment } from "../../Microsoft.Extensions.FileSystemGlobbing.Internal/internal/index.js";
import type { List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, StringComparison } from "@tsonic/dotnet/System/internal/index.js";

export interface CurrentPathSegment$instance extends Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PathSegments_CurrentPathSegment: never;

    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly CanProduceStem: boolean;
    Match(value: string): boolean;
}


export const CurrentPathSegment: {
    new(): CurrentPathSegment;
};


export interface __CurrentPathSegment$views {
    As_IPathSegment(): Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance;
}

export type CurrentPathSegment = CurrentPathSegment$instance & __CurrentPathSegment$views;


export interface LiteralPathSegment$instance extends Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PathSegments_LiteralPathSegment: never;

    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly CanProduceStem: boolean;
    readonly Value: string;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Match(value: string): boolean;
}


export const LiteralPathSegment: {
    new(value: string, comparisonType: StringComparison): LiteralPathSegment;
};


export interface __LiteralPathSegment$views {
    As_IPathSegment(): Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance;
}

export type LiteralPathSegment = LiteralPathSegment$instance & __LiteralPathSegment$views;


export interface ParentPathSegment$instance extends Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PathSegments_ParentPathSegment: never;

    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly CanProduceStem: boolean;
    Match(value: string): boolean;
}


export const ParentPathSegment: {
    new(): ParentPathSegment;
};


export interface __ParentPathSegment$views {
    As_IPathSegment(): Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance;
}

export type ParentPathSegment = ParentPathSegment$instance & __ParentPathSegment$views;


export interface RecursiveWildcardSegment$instance extends Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PathSegments_RecursiveWildcardSegment: never;

    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly CanProduceStem: boolean;
    Match(value: string): boolean;
}


export const RecursiveWildcardSegment: {
    new(): RecursiveWildcardSegment;
};


export interface __RecursiveWildcardSegment$views {
    As_IPathSegment(): Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance;
}

export type RecursiveWildcardSegment = RecursiveWildcardSegment$instance & __RecursiveWildcardSegment$views;


export interface WildcardPathSegment$instance extends Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PathSegments_WildcardPathSegment: never;

    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly BeginsWith: string;
    readonly CanProduceStem: boolean;
    readonly Contains: List_1<System_Internal.String>;
    readonly EndsWith: string;
    Match(value: string): boolean;
}


export const WildcardPathSegment: {
    new(beginsWith: string, contains: List_1<System_Internal.String>, endsWith: string, comparisonType: StringComparison): WildcardPathSegment;
    readonly MatchAll: WildcardPathSegment;
};


export interface __WildcardPathSegment$views {
    As_IPathSegment(): Microsoft_Extensions_FileSystemGlobbing_Internal_Internal.IPathSegment$instance;
}

export type WildcardPathSegment = WildcardPathSegment$instance & __WildcardPathSegment$views;


