// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Localization
// Assembly: Microsoft.Extensions.Localization, Microsoft.Extensions.Localization.Abstractions

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { ILogger, ILoggerFactory } from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { IOptions_1 } from "../../Microsoft.Extensions.Options/internal/index.js";
import type { IEnumerable_1, IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { CultureInfo } from "@tsonic/dotnet/System.Globalization/internal/index.js";
import type { Assembly, TypeInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import type { ResourceManager } from "@tsonic/dotnet/System.Resources/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Func_2, Object as ClrObject, String as ClrString, Type } from "@tsonic/dotnet/System/internal/index.js";

export interface IResourceNamesCache$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Localization_IResourceNamesCache: never;

    GetOrAdd(name: string, valueFactory: Func_2<System_Internal.String, IList_1<System_Internal.String> | null>): IList_1<System_Internal.String> | null;
}


export type IResourceNamesCache = IResourceNamesCache$instance;

export interface IStringLocalizer$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizer: never;

    get_Item2(name: string, ...arguments: unknown[]): LocalizedString;
    get_Item2(name: string): LocalizedString;
    GetAllStrings(includeParentCultures: boolean): IEnumerable_1<LocalizedString>;
}


export type IStringLocalizer = IStringLocalizer$instance;

export interface IStringLocalizer_1$instance<T extends unknown> extends IStringLocalizer {
    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizer_1: never;

    get_Item2(name: string, ...arguments: unknown[]): LocalizedString;
    get_Item2(name: string): LocalizedString;
    GetAllStrings(includeParentCultures: boolean): IEnumerable_1<LocalizedString>;
    get_Item(name: string): LocalizedString;
}


export interface IStringLocalizer_1$instance<T extends unknown> extends IStringLocalizer$instance {}

export type IStringLocalizer_1<T extends unknown> = IStringLocalizer_1$instance<T>;

export interface IStringLocalizerFactory$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizerFactory: never;

    Create(baseName: string, location: string): IStringLocalizer;
    Create(resourceSource: Type): IStringLocalizer;
}


export type IStringLocalizerFactory = IStringLocalizerFactory$instance;

export interface LocalizationOptions$instance {
    readonly __tsonic_type_Microsoft_Extensions_Localization_LocalizationOptions: never;

    ResourcesPath: string;
}


export const LocalizationOptions: {
    new(): LocalizationOptions;
};


export type LocalizationOptions = LocalizationOptions$instance;

export interface LocalizedString$instance {
    readonly __tsonic_type_Microsoft_Extensions_Localization_LocalizedString: never;

    readonly Name: string;
    readonly ResourceNotFound: boolean;
    readonly SearchedLocation: string | null;
    readonly Value: string;
    ToString(): string;
}


export const LocalizedString: {
    new(name: string, value: string): LocalizedString;
    new(name: string, value: string, resourceNotFound: boolean): LocalizedString;
    new(name: string, value: string, resourceNotFound: boolean, searchedLocation: string | null): LocalizedString;
};


export type LocalizedString = LocalizedString$instance;

export interface ResourceLocationAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_Extensions_Localization_ResourceLocationAttribute: never;

    readonly ResourceLocation: string;
}


export const ResourceLocationAttribute: {
    new(resourceLocation: string): ResourceLocationAttribute;
};


export type ResourceLocationAttribute = ResourceLocationAttribute$instance;

export interface ResourceManagerStringLocalizer$instance extends IStringLocalizer$instance {
    readonly __tsonic_type_Microsoft_Extensions_Localization_ResourceManagerStringLocalizer: never;

    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizer: never;

    get_Item(name: string): LocalizedString;
    get_Item(name: string, ...arguments: unknown[]): LocalizedString;
    GetAllStrings(includeParentCultures: boolean): IEnumerable_1<LocalizedString>;
}


export const ResourceManagerStringLocalizer: {
    new(resourceManager: ResourceManager, resourceAssembly: Assembly, baseName: string, resourceNamesCache: IResourceNamesCache, logger: ILogger): ResourceManagerStringLocalizer;
};


export interface __ResourceManagerStringLocalizer$views {
    As_IStringLocalizer(): IStringLocalizer$instance;
}

export type ResourceManagerStringLocalizer = ResourceManagerStringLocalizer$instance & __ResourceManagerStringLocalizer$views;


export interface ResourceManagerStringLocalizerFactory$instance extends IStringLocalizerFactory$instance {
    readonly __tsonic_type_Microsoft_Extensions_Localization_ResourceManagerStringLocalizerFactory: never;

    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizerFactory: never;

    Create(resourceSource: Type): IStringLocalizer;
    Create(baseName: string, location: string): IStringLocalizer;
    CreateResourceManagerStringLocalizer(assembly: Assembly, baseName: string): ResourceManagerStringLocalizer;
    GetResourceLocationAttribute(assembly: Assembly): ResourceLocationAttribute | null;
    GetResourcePrefix(typeInfo: TypeInfo): string;
    GetResourcePrefix(typeInfo: TypeInfo, baseNamespace: string | null, resourcesRelativePath: string | null): string;
    GetResourcePrefix(baseResourceName: string, baseNamespace: string): string;
    GetResourcePrefix(location: string, baseName: string, resourceLocation: string): string;
    GetRootNamespaceAttribute(assembly: Assembly): RootNamespaceAttribute | null;
}


export const ResourceManagerStringLocalizerFactory: {
    new(localizationOptions: IOptions_1<LocalizationOptions>, loggerFactory: ILoggerFactory): ResourceManagerStringLocalizerFactory;
};


export interface __ResourceManagerStringLocalizerFactory$views {
    As_IStringLocalizerFactory(): IStringLocalizerFactory$instance;
}

export type ResourceManagerStringLocalizerFactory = ResourceManagerStringLocalizerFactory$instance & __ResourceManagerStringLocalizerFactory$views;


export interface ResourceNamesCache$instance extends IResourceNamesCache$instance {
    readonly __tsonic_type_Microsoft_Extensions_Localization_ResourceNamesCache: never;

    readonly __tsonic_iface_Microsoft_Extensions_Localization_IResourceNamesCache: never;

    GetOrAdd(name: string, valueFactory: Func_2<System_Internal.String, IList_1<System_Internal.String> | null>): IList_1<System_Internal.String> | null;
}


export const ResourceNamesCache: {
    new(): ResourceNamesCache;
};


export interface __ResourceNamesCache$views {
    As_IResourceNamesCache(): IResourceNamesCache$instance;
}

export type ResourceNamesCache = ResourceNamesCache$instance & __ResourceNamesCache$views;


export interface RootNamespaceAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_Extensions_Localization_RootNamespaceAttribute: never;

    readonly RootNamespace: string;
}


export const RootNamespaceAttribute: {
    new(rootNamespace: string): RootNamespaceAttribute;
};


export type RootNamespaceAttribute = RootNamespaceAttribute$instance;

export interface StringLocalizer_1$instance<TResourceSource extends unknown> extends IStringLocalizer_1<TResourceSource>, IStringLocalizer_1$instance<TResourceSource> {
    readonly __tsonic_type_Microsoft_Extensions_Localization_StringLocalizer_1: never;

    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizer: never;
    readonly __tsonic_iface_Microsoft_Extensions_Localization_IStringLocalizer_1: never;

    get_Item(name: string): LocalizedString;
    get_Item(name: string, ...arguments: unknown[]): LocalizedString;
    GetAllStrings(includeParentCultures: boolean): IEnumerable_1<LocalizedString>;
}


export const StringLocalizer_1: {
    new<TResourceSource extends unknown>(factory: IStringLocalizerFactory): StringLocalizer_1<TResourceSource>;
};


export interface __StringLocalizer_1$views<TResourceSource extends unknown> {
    As_IStringLocalizer(): IStringLocalizer$instance;
}

export type StringLocalizer_1<TResourceSource extends unknown> = StringLocalizer_1$instance<TResourceSource> & __StringLocalizer_1$views<TResourceSource>;


export abstract class StringLocalizerExtensions$instance {
    static GetAllStrings(stringLocalizer: IStringLocalizer): IEnumerable_1<LocalizedString>;
    static GetString(stringLocalizer: IStringLocalizer, name: string, ...arguments: unknown[]): LocalizedString;
    static GetString(stringLocalizer: IStringLocalizer, name: string): LocalizedString;
}


export type StringLocalizerExtensions = StringLocalizerExtensions$instance;

