// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.ObjectPool
// Assembly: Microsoft.Extensions.ObjectPool

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, Void } from "@tsonic/dotnet/System.js";
import * as System_Text_Internal from "@tsonic/dotnet/System.Text.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text.js";

export interface IPooledObjectPolicy_1$instance<T> {
    create(): T;
    return_(obj: T): boolean;
}


export type IPooledObjectPolicy_1<T> = IPooledObjectPolicy_1$instance<T>;

export interface IResettable$instance {
    tryReset(): boolean;
}


export type IResettable = IResettable$instance;

export interface DefaultObjectPool_1$instance<T> extends ObjectPool_1<T> {
    get_(): T;
    return_(obj: T): void;
}


export const DefaultObjectPool_1: {
    new<T>(policy: IPooledObjectPolicy_1<T>): DefaultObjectPool_1<T>;
    new<T>(policy: IPooledObjectPolicy_1<T>, maximumRetained: int): DefaultObjectPool_1<T>;
};


export type DefaultObjectPool_1<T> = DefaultObjectPool_1$instance<T>;

export interface DefaultObjectPoolProvider$instance extends ObjectPoolProvider {
    maximumRetained: int;
    create<T>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
    create<T>(): ObjectPool_1<T>;
}


export const DefaultObjectPoolProvider: {
    new(): DefaultObjectPoolProvider;
};


export type DefaultObjectPoolProvider = DefaultObjectPoolProvider$instance;

export interface DefaultPooledObjectPolicy_1$instance<T> extends PooledObjectPolicy_1$instance<T> {
    create(): T;
    return_(obj: T): boolean;
}


export const DefaultPooledObjectPolicy_1: {
    new<T>(): DefaultPooledObjectPolicy_1<T>;
};


export interface __DefaultPooledObjectPolicy_1$views<T> {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<T>;
}

export type DefaultPooledObjectPolicy_1<T> = DefaultPooledObjectPolicy_1$instance<T> & __DefaultPooledObjectPolicy_1$views<T>;


export interface LeakTrackingObjectPool_1$instance<T> extends ObjectPool_1<T> {
    get_(): T;
    return_(obj: T): void;
}


export const LeakTrackingObjectPool_1: {
    new<T>(inner: ObjectPool_1<T>): LeakTrackingObjectPool_1<T>;
};


export type LeakTrackingObjectPool_1<T> = LeakTrackingObjectPool_1$instance<T>;

export interface LeakTrackingObjectPoolProvider$instance extends ObjectPoolProvider {
    create<T>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
    create<T>(): ObjectPool_1<T>;
}


export const LeakTrackingObjectPoolProvider: {
    new(inner: ObjectPoolProvider): LeakTrackingObjectPoolProvider;
};


export type LeakTrackingObjectPoolProvider = LeakTrackingObjectPoolProvider$instance;

export interface ObjectPool_1$instance<T> {
    get_(): T;
    return_(obj: T): void;
}


export const ObjectPool_1: {
};


export type ObjectPool_1<T> = ObjectPool_1$instance<T>;

export interface ObjectPoolProvider$instance {
    create<T>(): ObjectPool_1<T>;
    create<T>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
}


export const ObjectPoolProvider: {
};


export type ObjectPoolProvider = ObjectPoolProvider$instance;

export interface PooledObjectPolicy_1$instance<T> {
    create(): T;
    return_(obj: T): boolean;
}


export const PooledObjectPolicy_1: {
};


export interface __PooledObjectPolicy_1$views<T> {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<T>;
}

export interface PooledObjectPolicy_1$instance<T> extends IPooledObjectPolicy_1$instance<T> {}

export type PooledObjectPolicy_1<T> = PooledObjectPolicy_1$instance<T> & __PooledObjectPolicy_1$views<T>;


export interface StringBuilderPooledObjectPolicy$instance extends PooledObjectPolicy_1$instance<StringBuilder> {
    initialCapacity: int;
    maximumRetainedCapacity: int;
}


export const StringBuilderPooledObjectPolicy: {
    new(): StringBuilderPooledObjectPolicy;
};


export interface __StringBuilderPooledObjectPolicy$views {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<StringBuilder>;
}

export type StringBuilderPooledObjectPolicy = StringBuilderPooledObjectPolicy$instance & __StringBuilderPooledObjectPolicy$views;


export abstract class ObjectPool$instance {
    static create<T>(policy?: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
}


export type ObjectPool = ObjectPool$instance;

export abstract class ObjectPoolProviderExtensions$instance {
    static createStringBuilderPool(provider: ObjectPoolProvider, initialCapacity: int, maximumRetainedCapacity: int): ObjectPool_1<StringBuilder>;
    static createStringBuilderPool(provider: ObjectPoolProvider): ObjectPool_1<StringBuilder>;
}


export type ObjectPoolProviderExtensions = ObjectPoolProviderExtensions$instance;

