// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Extensions.ObjectPool
// Assembly: Microsoft.Extensions.ObjectPool

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Text_Internal from "@tsonic/dotnet/System.Text/internal/index.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IPooledObjectPolicy_1$instance<T extends unknown> {
    readonly __tsonic_iface_Microsoft_Extensions_ObjectPool_IPooledObjectPolicy_1: never;

    Create(): T;
    Return(obj: T): boolean;
}


export type IPooledObjectPolicy_1<T extends unknown> = IPooledObjectPolicy_1$instance<T>;

export interface IResettable$instance {
    readonly __tsonic_iface_Microsoft_Extensions_ObjectPool_IResettable: never;

    TryReset(): boolean;
}


export type IResettable = IResettable$instance;

export interface DefaultObjectPool_1$instance<T extends (object | null)> extends ObjectPool_1<T> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_DefaultObjectPool_1: never;

    Get(): T;
    Return(obj: T): void;
}


export const DefaultObjectPool_1: {
    new<T extends (object | null)>(policy: IPooledObjectPolicy_1<T>): DefaultObjectPool_1<T>;
    new<T extends (object | null)>(policy: IPooledObjectPolicy_1<T>, maximumRetained: int): DefaultObjectPool_1<T>;
};


export type DefaultObjectPool_1<T extends (object | null)> = DefaultObjectPool_1$instance<T>;

export interface DefaultObjectPoolProvider$instance extends ObjectPoolProvider {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_DefaultObjectPoolProvider: never;

    MaximumRetained: int;
    Create<T extends (object | null)>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
    Create<T extends (object | null)>(): ObjectPool_1<T>;
}


export const DefaultObjectPoolProvider: {
    new(): DefaultObjectPoolProvider;
};


export type DefaultObjectPoolProvider = DefaultObjectPoolProvider$instance;

export interface DefaultPooledObjectPolicy_1$instance<T extends (object | null)> extends PooledObjectPolicy_1$instance<T>, IPooledObjectPolicy_1$instance<T> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_DefaultPooledObjectPolicy_1: never;

    readonly __tsonic_iface_Microsoft_Extensions_ObjectPool_IPooledObjectPolicy_1: never;

    Create(): T;
    Return(obj: T): boolean;
}


export const DefaultPooledObjectPolicy_1: {
    new<T extends (object | null)>(): DefaultPooledObjectPolicy_1<T>;
};


export interface __DefaultPooledObjectPolicy_1$views<T extends (object | null)> {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<T>;
}

export type DefaultPooledObjectPolicy_1<T extends (object | null)> = DefaultPooledObjectPolicy_1$instance<T> & __DefaultPooledObjectPolicy_1$views<T>;


export interface LeakTrackingObjectPool_1$instance<T extends (object | null)> extends ObjectPool_1<T> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_LeakTrackingObjectPool_1: never;

    Get(): T;
    Return(obj: T): void;
}


export const LeakTrackingObjectPool_1: {
    new<T extends (object | null)>(inner: ObjectPool_1<T>): LeakTrackingObjectPool_1<T>;
};


export type LeakTrackingObjectPool_1<T extends (object | null)> = LeakTrackingObjectPool_1$instance<T>;

export interface LeakTrackingObjectPoolProvider$instance extends ObjectPoolProvider {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_LeakTrackingObjectPoolProvider: never;

    Create<T extends (object | null)>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
    Create<T extends (object | null)>(): ObjectPool_1<T>;
}


export const LeakTrackingObjectPoolProvider: {
    new(inner: ObjectPoolProvider): LeakTrackingObjectPoolProvider;
};


export type LeakTrackingObjectPoolProvider = LeakTrackingObjectPoolProvider$instance;

export interface ObjectPool_1$instance<T extends (object | null)> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_ObjectPool_1: never;

    Get(): T;
    Return(obj: T): void;
}


export const ObjectPool_1: (abstract new<T extends (object | null)>() => ObjectPool_1<T>) & {
};


export type ObjectPool_1<T extends (object | null)> = ObjectPool_1$instance<T>;

export interface ObjectPoolProvider$instance {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_ObjectPoolProvider: never;

    Create<T extends (object | null)>(): ObjectPool_1<T>;
    Create<T extends (object | null)>(policy: IPooledObjectPolicy_1<T>): ObjectPool_1<T>;
}


export const ObjectPoolProvider: (abstract new() => ObjectPoolProvider) & {
};


export type ObjectPoolProvider = ObjectPoolProvider$instance;

export interface PooledObjectPolicy_1$instance<T extends unknown> extends IPooledObjectPolicy_1$instance<T> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_PooledObjectPolicy_1: never;

    readonly __tsonic_iface_Microsoft_Extensions_ObjectPool_IPooledObjectPolicy_1: never;

    Create(): T;
    Return(obj: T): boolean;
}


export const PooledObjectPolicy_1: (abstract new<T extends unknown>() => PooledObjectPolicy_1<T>) & {
};


export interface __PooledObjectPolicy_1$views<T extends unknown> {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<T>;
}

export type PooledObjectPolicy_1<T extends unknown> = PooledObjectPolicy_1$instance<T> & __PooledObjectPolicy_1$views<T>;


export interface StringBuilderPooledObjectPolicy$instance extends PooledObjectPolicy_1$instance<StringBuilder>, IPooledObjectPolicy_1$instance<StringBuilder> {
    readonly __tsonic_type_Microsoft_Extensions_ObjectPool_StringBuilderPooledObjectPolicy: never;

    readonly __tsonic_iface_Microsoft_Extensions_ObjectPool_IPooledObjectPolicy_1: never;

    InitialCapacity: int;
    MaximumRetainedCapacity: int;
    Create(): StringBuilder;
    Return(obj: StringBuilder): boolean;
}


export const StringBuilderPooledObjectPolicy: {
    new(): StringBuilderPooledObjectPolicy;
};


export interface __StringBuilderPooledObjectPolicy$views {
    As_IPooledObjectPolicy_1(): IPooledObjectPolicy_1$instance<StringBuilder>;
}

export type StringBuilderPooledObjectPolicy = StringBuilderPooledObjectPolicy$instance & __StringBuilderPooledObjectPolicy$views;


export abstract class ObjectPool$instance {
    static Create<T extends (object | null)>(policy?: IPooledObjectPolicy_1<T> | null): ObjectPool_1<T>;
}


export type ObjectPool = ObjectPool$instance;

export abstract class ObjectPoolProviderExtensions$instance {
    static CreateStringBuilderPool(provider: ObjectPoolProvider, initialCapacity: int, maximumRetainedCapacity: int): ObjectPool_1<StringBuilder>;
    static CreateStringBuilderPool(provider: ObjectPoolProvider): ObjectPool_1<StringBuilder>;
}


export type ObjectPoolProviderExtensions = ObjectPoolProviderExtensions$instance;
