// Generated by tsbindgen - Architecture
// Namespace: System.Security.Cryptography
// Assembly: System.Private.CoreLib, System.Security.Cryptography, System.Security.Cryptography.Pkcs

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { ICollection, IEnumerable, IEnumerator } from "@tsonic/dotnet/System.Collections.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, Void } from "@tsonic/dotnet/System.js";
import type { AsnEncodedData, AsnEncodedDataCollection, Oid } from "@tsonic/dotnet/System.Security.Cryptography.js";

export interface CryptographicAttributeObject$instance {
    readonly Oid: Oid;
    readonly Values: AsnEncodedDataCollection;
}


export const CryptographicAttributeObject: {
    new(oid: Oid): CryptographicAttributeObject;
    new(oid: Oid, values: AsnEncodedDataCollection): CryptographicAttributeObject;
};


export type CryptographicAttributeObject = CryptographicAttributeObject$instance;

export interface CryptographicAttributeObjectCollection$instance {
    readonly Count: int;
    readonly IsSynchronized: boolean;
    readonly Item: CryptographicAttributeObject;
    readonly SyncRoot: unknown;
    Add(asnEncodedData: AsnEncodedData): int;
    Add(attribute: CryptographicAttributeObject): int;
    CopyTo(array: CryptographicAttributeObject[], index: int): void;
    GetEnumerator(): CryptographicAttributeObjectEnumerator;
    Remove(attribute: CryptographicAttributeObject): void;
}


export const CryptographicAttributeObjectCollection: {
    new(): CryptographicAttributeObjectCollection;
    new(attribute: CryptographicAttributeObject): CryptographicAttributeObjectCollection;
};


export type CryptographicAttributeObjectCollection = CryptographicAttributeObjectCollection$instance;

export interface CryptographicAttributeObjectEnumerator$instance {
    readonly Current: CryptographicAttributeObject;
    MoveNext(): boolean;
    Reset(): void;
}


export const CryptographicAttributeObjectEnumerator: {
    new(): CryptographicAttributeObjectEnumerator;
};


export type CryptographicAttributeObjectEnumerator = CryptographicAttributeObjectEnumerator$instance;

