// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileProviders.Internal
// Assembly: Microsoft.Extensions.FileProviders.Physical

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { ExclusionFilters } from "../../Microsoft.Extensions.FileProviders.Physical/internal/index.js";
import * as Microsoft_Extensions_FileProviders_Internal from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import type { IDirectoryContents, IFileInfo } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export interface PhysicalDirectoryContents$instance {
    readonly exists: boolean;
    getEnumerator(): IEnumerator<IFileInfo>;
}


export const PhysicalDirectoryContents: {
    new(directory: string): PhysicalDirectoryContents;
    new(directory: string, filters: ExclusionFilters): PhysicalDirectoryContents;
};


export interface __PhysicalDirectoryContents$views {
    As_IDirectoryContents(): Microsoft_Extensions_FileProviders_Internal.IDirectoryContents$instance;
}

export interface PhysicalDirectoryContents$instance extends Microsoft_Extensions_FileProviders_Internal.IDirectoryContents$instance {}

export type PhysicalDirectoryContents = PhysicalDirectoryContents$instance & __PhysicalDirectoryContents$views;


