// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Caching.Hybrid
// Assembly: Microsoft.Extensions.Caching.Abstractions

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IBufferWriter, ReadOnlySequence } from "@tsonic/dotnet/System.Buffers.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Byte, Char, Enum, Func, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, ReadOnlySpan, String as ClrString, TimeSpan, Void } from "@tsonic/dotnet/System.js";
import type { DefaultInterpolatedStringHandler } from "@tsonic/dotnet/System.Runtime.CompilerServices.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";

export enum HybridCacheEntryFlags {
    None = 0,
    DisableLocalCacheRead = 1,
    DisableLocalCacheWrite = 2,
    DisableLocalCache = 3,
    DisableDistributedCacheRead = 4,
    DisableDistributedCacheWrite = 8,
    DisableDistributedCache = 12,
    DisableUnderlyingData = 16,
    DisableCompression = 32
}


export interface IHybridCacheSerializer_1$instance<T> {
    Deserialize(source: ReadOnlySequence<System_Internal.Byte>): T;
    Serialize(value: T, target: IBufferWriter<System_Internal.Byte>): void;
}


export type IHybridCacheSerializer_1<T> = IHybridCacheSerializer_1$instance<T>;

export interface IHybridCacheSerializerFactory$instance {
    TryCreateSerializer<T>(serializer: IHybridCacheSerializer_1<T>): boolean;
}


export type IHybridCacheSerializerFactory = IHybridCacheSerializerFactory$instance;

export interface HybridCache$instance {
    GetOrCreateAsync<TState, T>(key: string, state: TState, factory: Func<TState, CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    GetOrCreateAsync<T>(key: string, factory: Func<CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    GetOrCreateAsync<T>(key: ReadOnlySpan<System_Internal.Char>, factory: Func<CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    GetOrCreateAsync<TState, T>(key: ReadOnlySpan<System_Internal.Char>, state: TState, factory: Func<TState, CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    GetOrCreateAsync<T>(key: DefaultInterpolatedStringHandler, factory: Func<CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    GetOrCreateAsync<TState, T>(key: DefaultInterpolatedStringHandler, state: TState, factory: Func<TState, CancellationToken, ValueTask<T>>, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask<T>;
    RemoveAsync(key: string, cancellationToken?: CancellationToken): ValueTask;
    RemoveAsync(keys: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask;
    RemoveByTagAsync(tags: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask;
    RemoveByTagAsync(tag: string, cancellationToken?: CancellationToken): ValueTask;
    SetAsync<T>(key: string, value: T, options?: HybridCacheEntryOptions, tags?: IEnumerable<System_Internal.String>, cancellationToken?: CancellationToken): ValueTask;
}


export const HybridCache: {
    new(): HybridCache;
};


export type HybridCache = HybridCache$instance;

export interface HybridCacheEntryOptions$instance {
    Expiration: Nullable<TimeSpan>;
    Flags: Nullable<HybridCacheEntryFlags>;
    LocalCacheExpiration: Nullable<TimeSpan>;
}


export const HybridCacheEntryOptions: {
    new(): HybridCacheEntryOptions;
};


export type HybridCacheEntryOptions = HybridCacheEntryOptions$instance;

