// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Diagnostics.Metrics.Configuration
// Assembly: Microsoft.Extensions.Diagnostics

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { IConfiguration } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { String as ClrString } from "@tsonic/dotnet/System.js";

export interface IMetricListenerConfigurationFactory$instance {
    getConfiguration(listenerName: string): IConfiguration;
}


export type IMetricListenerConfigurationFactory = IMetricListenerConfigurationFactory$instance;

