// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Logging.Abstractions
// Assembly: Microsoft.Extensions.Logging.Abstractions

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_Extensions_Logging_Internal from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { EventId, ILogger, ILogger_1, ILoggerFactory, ILoggerProvider, LogLevel } from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { IEnumerable_1, IReadOnlyList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ActivitySpanId, ActivityTraceId } from "@tsonic/dotnet/System.Diagnostics/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, DateTimeOffset, Exception, Func_3, IDisposable, Int32, Nullable_1, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IBufferedLogger$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Logging_Abstractions_IBufferedLogger: never;

    LogRecords(records: IEnumerable_1<BufferedLogRecord>): void;
}


export type IBufferedLogger = IBufferedLogger$instance;

export interface LogEntry_1$instance<TState> {
    readonly Category: string;
    readonly EventId: EventId;
    readonly Exception: Exception | undefined;
    readonly Formatter: Func_3<TState, Exception | undefined, System_Internal.String>;
    readonly LogLevel: LogLevel;
    readonly State: TState;
}


export const LogEntry_1: {
    new<TState>(logLevel: LogLevel, category: string, eventId: EventId, state: TState, exception: Exception, formatter: Func_3<TState, Exception, System_Internal.String>): LogEntry_1<TState>;
};


export type LogEntry_1<TState> = LogEntry_1$instance<TState>;

export interface BufferedLogRecord$instance {
    readonly ActivitySpanId: Nullable_1<ActivitySpanId>;
    readonly ActivityTraceId: Nullable_1<ActivityTraceId>;
    readonly Attributes: IReadOnlyList_1<KeyValuePair_2<System_Internal.String, unknown>>;
    readonly EventId: EventId;
    readonly Exception: string | undefined;
    readonly FormattedMessage: string | undefined;
    readonly LogLevel: LogLevel;
    readonly ManagedThreadId: Nullable_1<System_Internal.Int32>;
    readonly MessageTemplate: string | undefined;
    readonly Timestamp: DateTimeOffset;
}


export const BufferedLogRecord: (abstract new() => BufferedLogRecord) & {
};


export type BufferedLogRecord = BufferedLogRecord$instance;

export interface NullLogger$instance extends Microsoft_Extensions_Logging_Internal.ILogger$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILogger: never;

    BeginScope<TState>(state: TState): IDisposable;
    IsEnabled(logLevel: LogLevel): boolean;
    Log<TState>(logLevel: LogLevel, eventId: EventId, state: TState, exception: Exception, formatter: Func_3<TState, Exception, System_Internal.String>): void;
}


export const NullLogger: {
    readonly Instance: NullLogger;
};


export interface __NullLogger$views {
    As_ILogger(): Microsoft_Extensions_Logging_Internal.ILogger$instance;
}

export type NullLogger = NullLogger$instance & __NullLogger$views;


export interface NullLogger_1$instance<T> extends ILogger_1<T> {
    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILogger: never;
    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILogger_1: never;

    BeginScope<TState>(state: TState): IDisposable;
    IsEnabled(logLevel: LogLevel): boolean;
    Log<TState>(logLevel: LogLevel, eventId: EventId, state: TState, exception: Exception, formatter: Func_3<TState, Exception, System_Internal.String>): void;
}


export const NullLogger_1: {
    new<T>(): NullLogger_1<T>;
    readonly Instance: unknown;
};


export interface __NullLogger_1$views<T> {
    As_ILogger(): Microsoft_Extensions_Logging_Internal.ILogger$instance;
}

export type NullLogger_1<T> = NullLogger_1$instance<T> & __NullLogger_1$views<T>;


export interface NullLoggerFactory$instance extends Microsoft_Extensions_Logging_Internal.ILoggerFactory$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILoggerFactory: never;
    readonly __tsonic_iface_System_IDisposable: never;

    AddProvider(provider: ILoggerProvider): void;
    CreateLogger(name: string): ILogger;
    Dispose(): void;
}


export const NullLoggerFactory: {
    new(): NullLoggerFactory;
    readonly Instance: NullLoggerFactory;
};


export interface __NullLoggerFactory$views {
    As_ILoggerFactory(): Microsoft_Extensions_Logging_Internal.ILoggerFactory$instance;
}

export type NullLoggerFactory = NullLoggerFactory$instance & __NullLoggerFactory$views;


export interface NullLoggerProvider$instance extends Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance {
    readonly __tsonic_iface_Microsoft_Extensions_Logging_ILoggerProvider: never;
    readonly __tsonic_iface_System_IDisposable: never;

    CreateLogger(categoryName: string): ILogger;
    Dispose(): void;
}


export const NullLoggerProvider: {
    readonly Instance: NullLoggerProvider;
};


export interface __NullLoggerProvider$views {
    As_ILoggerProvider(): Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance;
}

export type NullLoggerProvider = NullLoggerProvider$instance & __NullLoggerProvider$views;


