// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileProviders.Physical
// Assembly: Microsoft.Extensions.FileProviders.Physical

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_Extensions_FileProviders_Internal from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import type { IDirectoryContents, IFileInfo } from "../../Microsoft.Extensions.FileProviders/internal/index.js";
import * as Microsoft_Extensions_Primitives_Internal from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import type { DirectoryInfo, FileInfo, FileSystemWatcher, Stream } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, DateTimeOffset, Enum, IComparable, IConvertible, IDisposable, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export enum ExclusionFilters {
    Sensitive = 7,
    DotPrefixed = 1,
    Hidden = 2,
    System = 4,
    None = 0
}


export interface PhysicalDirectoryInfo$instance {
    readonly Exists: boolean;
    readonly IsDirectory: boolean;
    readonly LastModified: DateTimeOffset;
    readonly Length: long;
    readonly Name: string;
    readonly PhysicalPath: string;
    CreateReadStream(): Stream;
    GetEnumerator(): IEnumerator<IFileInfo>;
}


export const PhysicalDirectoryInfo: {
    new(info: DirectoryInfo): PhysicalDirectoryInfo;
};


export interface __PhysicalDirectoryInfo$views {
    As_IDirectoryContents(): Microsoft_Extensions_FileProviders_Internal.IDirectoryContents$instance;
    As_IFileInfo(): Microsoft_Extensions_FileProviders_Internal.IFileInfo$instance;
}

export interface PhysicalDirectoryInfo$instance extends Microsoft_Extensions_FileProviders_Internal.IDirectoryContents$instance, Microsoft_Extensions_FileProviders_Internal.IFileInfo$instance {}

export type PhysicalDirectoryInfo = PhysicalDirectoryInfo$instance & __PhysicalDirectoryInfo$views;


export interface PhysicalFileInfo$instance {
    readonly Exists: boolean;
    readonly IsDirectory: boolean;
    readonly LastModified: DateTimeOffset;
    readonly Length: long;
    readonly Name: string;
    readonly PhysicalPath: string;
    CreateReadStream(): Stream;
}


export const PhysicalFileInfo: {
    new(info: FileInfo): PhysicalFileInfo;
};


export interface __PhysicalFileInfo$views {
    As_IFileInfo(): Microsoft_Extensions_FileProviders_Internal.IFileInfo$instance;
}

export interface PhysicalFileInfo$instance extends Microsoft_Extensions_FileProviders_Internal.IFileInfo$instance {}

export type PhysicalFileInfo = PhysicalFileInfo$instance & __PhysicalFileInfo$views;


export interface PhysicalFilesWatcher$instance {
    CreateFileChangeToken(filter: string): IChangeToken;
    Dispose(): void;
}


export const PhysicalFilesWatcher: {
    new(root: string, fileSystemWatcher: FileSystemWatcher, pollForChanges: boolean): PhysicalFilesWatcher;
    new(root: string, fileSystemWatcher: FileSystemWatcher, pollForChanges: boolean, filters: ExclusionFilters): PhysicalFilesWatcher;
};


export type PhysicalFilesWatcher = PhysicalFilesWatcher$instance;

export interface PollingFileChangeToken$instance {
    readonly ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
    RegisterChangeCallback(callback: Action<unknown>, state: unknown): IDisposable;
}


export const PollingFileChangeToken: {
    new(fileInfo: FileInfo): PollingFileChangeToken;
};


export interface __PollingFileChangeToken$views {
    As_IChangeToken(): Microsoft_Extensions_Primitives_Internal.IChangeToken$instance;
}

export interface PollingFileChangeToken$instance extends Microsoft_Extensions_Primitives_Internal.IChangeToken$instance {}

export type PollingFileChangeToken = PollingFileChangeToken$instance & __PollingFileChangeToken$views;


export interface PollingWildCardChangeToken$instance {
    readonly ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
}


export const PollingWildCardChangeToken: {
    new(root: string, pattern: string): PollingWildCardChangeToken;
};


export interface __PollingWildCardChangeToken$views {
    As_IChangeToken(): Microsoft_Extensions_Primitives_Internal.IChangeToken$instance;
}

export interface PollingWildCardChangeToken$instance extends Microsoft_Extensions_Primitives_Internal.IChangeToken$instance {}

export type PollingWildCardChangeToken = PollingWildCardChangeToken$instance & __PollingWildCardChangeToken$views;


