// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.WebEncoders.Testing
// Assembly: Microsoft.Extensions.WebEncoders

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { TextWriter } from "@tsonic/dotnet/System.IO.js";
import type { Boolean as ClrBoolean, Char, Int32, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import * as System_Text_Encodings_Web_Internal from "@tsonic/dotnet/System.Text.Encodings.Web.js";
import type { HtmlEncoder, JavaScriptEncoder, UrlEncoder } from "@tsonic/dotnet/System.Text.Encodings.Web.js";

export interface HtmlTestEncoder$instance extends HtmlEncoder {
    readonly MaxOutputCharactersPerInputCharacter: int;
    Encode(value: string): string;
    Encode(output: TextWriter, value: char[], startIndex: int, characterCount: int): void;
    Encode(output: TextWriter, value: string, startIndex: int, characterCount: int): void;
    FindFirstCharacterToEncode(text: ptr<char>, textLength: int): int;
    TryEncodeUnicodeScalar(unicodeScalar: int, buffer: ptr<char>, bufferLength: int, numberOfCharactersWritten: int): boolean;
    WillEncode(unicodeScalar: int): boolean;
}


export const HtmlTestEncoder: {
    new(): HtmlTestEncoder;
};


export type HtmlTestEncoder = HtmlTestEncoder$instance;

export interface JavaScriptTestEncoder$instance extends JavaScriptEncoder {
    readonly MaxOutputCharactersPerInputCharacter: int;
    Encode(value: string): string;
    Encode(output: TextWriter, value: char[], startIndex: int, characterCount: int): void;
    Encode(output: TextWriter, value: string, startIndex: int, characterCount: int): void;
    FindFirstCharacterToEncode(text: ptr<char>, textLength: int): int;
    TryEncodeUnicodeScalar(unicodeScalar: int, buffer: ptr<char>, bufferLength: int, numberOfCharactersWritten: int): boolean;
    WillEncode(unicodeScalar: int): boolean;
}


export const JavaScriptTestEncoder: {
    new(): JavaScriptTestEncoder;
};


export type JavaScriptTestEncoder = JavaScriptTestEncoder$instance;

export interface UrlTestEncoder$instance extends UrlEncoder {
    readonly MaxOutputCharactersPerInputCharacter: int;
    Encode(value: string): string;
    Encode(output: TextWriter, value: char[], startIndex: int, characterCount: int): void;
    Encode(output: TextWriter, value: string, startIndex: int, characterCount: int): void;
    FindFirstCharacterToEncode(text: ptr<char>, textLength: int): int;
    TryEncodeUnicodeScalar(unicodeScalar: int, buffer: ptr<char>, bufferLength: int, numberOfCharactersWritten: int): boolean;
    WillEncode(unicodeScalar: int): boolean;
}


export const UrlTestEncoder: {
    new(): UrlTestEncoder;
};


export type UrlTestEncoder = UrlTestEncoder$instance;

