// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.Logging.Console
// Assembly: Microsoft.Extensions.Logging.Console

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IConfiguration } from "../../Microsoft.Extensions.Configuration/internal/index.js";
import type { LogEntry_1 } from "../../Microsoft.Extensions.Logging.Abstractions/internal/index.js";
import * as Microsoft_Extensions_Logging_Internal from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { IExternalScopeProvider, ILogger, ILoggerProvider, ISupportExternalScope, LogLevel } from "../../Microsoft.Extensions.Logging/internal/index.js";
import type { IOptionsMonitor_1 } from "../../Microsoft.Extensions.Options/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IDictionary, IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { TextWriter } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IDisposable, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { JsonWriterOptions } from "@tsonic/dotnet/System.Text.Json.js";

export enum ConsoleLoggerFormat {
    Default = 0,
    Systemd = 1
}


export enum ConsoleLoggerQueueFullMode {
    Wait = 0,
    DropWrite = 1
}


export enum LoggerColorBehavior {
    Default = 0,
    Enabled = 1,
    Disabled = 2
}


export interface IConsoleLoggerSettings$instance {
    readonly IncludeScopes: boolean;
    readonly ChangeToken: IChangeToken | undefined;
    Reload(): IConsoleLoggerSettings;
    TryGetSwitch(name: string, level: LogLevel): boolean;
}


export type IConsoleLoggerSettings = IConsoleLoggerSettings$instance;

export interface ConfigurationConsoleLoggerSettings$instance {
    readonly ChangeToken: IChangeToken | undefined;
    readonly IncludeScopes: boolean;
    Reload(): IConsoleLoggerSettings;
    TryGetSwitch(name: string, level: LogLevel): boolean;
}


export const ConfigurationConsoleLoggerSettings: {
    new(configuration: IConfiguration): ConfigurationConsoleLoggerSettings;
};


export interface __ConfigurationConsoleLoggerSettings$views {
    As_IConsoleLoggerSettings(): IConsoleLoggerSettings$instance;
}

export interface ConfigurationConsoleLoggerSettings$instance extends IConsoleLoggerSettings$instance {}

export type ConfigurationConsoleLoggerSettings = ConfigurationConsoleLoggerSettings$instance & __ConfigurationConsoleLoggerSettings$views;


export interface ConsoleFormatter$instance {
    readonly Name: string;
    Write<TState>(logEntry: LogEntry_1<TState>, scopeProvider: IExternalScopeProvider, textWriter: TextWriter): void;
}


export const ConsoleFormatter: {
};


export type ConsoleFormatter = ConsoleFormatter$instance;

export interface ConsoleFormatterOptions$instance {
    IncludeScopes: boolean;
    get TimestampFormat(): string | undefined;
    set TimestampFormat(value: string);
    UseUtcTimestamp: boolean;
}


export const ConsoleFormatterOptions: {
    new(): ConsoleFormatterOptions;
};


export type ConsoleFormatterOptions = ConsoleFormatterOptions$instance;

export interface ConsoleLoggerOptions$instance {
    DisableColors: boolean;
    Format: ConsoleLoggerFormat;
    get FormatterName(): string | undefined;
    set FormatterName(value: string);
    IncludeScopes: boolean;
    LogToStandardErrorThreshold: LogLevel;
    MaxQueueLength: int;
    QueueFullMode: ConsoleLoggerQueueFullMode;
    get TimestampFormat(): string | undefined;
    set TimestampFormat(value: string);
    UseUtcTimestamp: boolean;
}


export const ConsoleLoggerOptions: {
    new(): ConsoleLoggerOptions;
};


export type ConsoleLoggerOptions = ConsoleLoggerOptions$instance;

export interface ConsoleLoggerProvider$instance {
    CreateLogger(name: string): ILogger;
    Dispose(): void;
    SetScopeProvider(scopeProvider: IExternalScopeProvider): void;
}


export const ConsoleLoggerProvider: {
    new(options: IOptionsMonitor_1<ConsoleLoggerOptions>): ConsoleLoggerProvider;
    new(options: IOptionsMonitor_1<ConsoleLoggerOptions>, formatters: IEnumerable<ConsoleFormatter>): ConsoleLoggerProvider;
};


export interface __ConsoleLoggerProvider$views {
    As_ILoggerProvider(): Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance;
    As_ISupportExternalScope(): Microsoft_Extensions_Logging_Internal.ISupportExternalScope$instance;
}

export interface ConsoleLoggerProvider$instance extends Microsoft_Extensions_Logging_Internal.ILoggerProvider$instance, Microsoft_Extensions_Logging_Internal.ISupportExternalScope$instance {}

export type ConsoleLoggerProvider = ConsoleLoggerProvider$instance & __ConsoleLoggerProvider$views;


export interface ConsoleLoggerSettings$instance {
    get ChangeToken(): IChangeToken | undefined;
    set ChangeToken(value: IChangeToken);
    DisableColors: boolean;
    IncludeScopes: boolean;
    Switches: IDictionary<System_Internal.String, LogLevel>;
    Reload(): IConsoleLoggerSettings;
    TryGetSwitch(name: string, level: LogLevel): boolean;
}


export const ConsoleLoggerSettings: {
    new(): ConsoleLoggerSettings;
};


export interface __ConsoleLoggerSettings$views {
    As_IConsoleLoggerSettings(): IConsoleLoggerSettings$instance;
}

export type ConsoleLoggerSettings = ConsoleLoggerSettings$instance & __ConsoleLoggerSettings$views;


export interface JsonConsoleFormatterOptions$instance extends ConsoleFormatterOptions {
    JsonWriterOptions: JsonWriterOptions;
}


export const JsonConsoleFormatterOptions: {
    new(): JsonConsoleFormatterOptions;
};


export type JsonConsoleFormatterOptions = JsonConsoleFormatterOptions$instance;

export interface SimpleConsoleFormatterOptions$instance extends ConsoleFormatterOptions {
    ColorBehavior: LoggerColorBehavior;
    SingleLine: boolean;
}


export const SimpleConsoleFormatterOptions: {
    new(): SimpleConsoleFormatterOptions;
};


export type SimpleConsoleFormatterOptions = SimpleConsoleFormatterOptions$instance;

export abstract class ConsoleFormatterNames$instance {
    static readonly Simple: string;
    static readonly Json: string;
    static readonly Systemd: string;
}


export type ConsoleFormatterNames = ConsoleFormatterNames$instance;

