// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileProviders
// Assembly: Microsoft.Extensions.FileProviders.Abstractions, Microsoft.Extensions.FileProviders.Composite, Microsoft.Extensions.FileProviders.Embedded, Microsoft.Extensions.FileProviders.Physical

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { ExclusionFilters } from "../../Microsoft.Extensions.FileProviders.Physical/internal/index.js";
import * as Microsoft_Extensions_Primitives_Internal from "../../Microsoft.Extensions.Primitives/internal/index.js";
import type { IChangeToken } from "../../Microsoft.Extensions.Primitives/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import type { Stream } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, DateTimeOffset, IDisposable, Int64, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { Assembly } from "@tsonic/dotnet/System.Reflection.js";

export interface IDirectoryContents$instance extends IEnumerable__System_Collections_Generic<IFileInfo>, IEnumerable {
    readonly Exists: boolean;
}


export type IDirectoryContents = IDirectoryContents$instance;

export interface IFileInfo$instance {
    readonly Exists: boolean;
    readonly Length: long;
    readonly PhysicalPath: string;
    readonly Name: string;
    readonly LastModified: DateTimeOffset;
    readonly IsDirectory: boolean;
    CreateReadStream(): Stream;
}


export type IFileInfo = IFileInfo$instance;

export interface IFileProvider$instance {
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(filter: string): IChangeToken;
}


export type IFileProvider = IFileProvider$instance;

export interface CompositeFileProvider$instance {
    readonly FileProviders: IEnumerable__System_Collections_Generic<IFileProvider>;
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(pattern: string): IChangeToken;
}


export const CompositeFileProvider: {
    new(fileProviders: IFileProvider[]): CompositeFileProvider;
    new(fileProviders: IEnumerable__System_Collections_Generic<IFileProvider>): CompositeFileProvider;
};


export interface __CompositeFileProvider$views {
    As_IFileProvider(): IFileProvider$instance;
}

export interface CompositeFileProvider$instance extends IFileProvider$instance {}

export type CompositeFileProvider = CompositeFileProvider$instance & __CompositeFileProvider$views;


export interface EmbeddedFileProvider$instance {
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(pattern: string): IChangeToken;
}


export const EmbeddedFileProvider: {
    new(assembly: Assembly): EmbeddedFileProvider;
    new(assembly: Assembly, baseNamespace: string): EmbeddedFileProvider;
};


export interface __EmbeddedFileProvider$views {
    As_IFileProvider(): IFileProvider$instance;
}

export interface EmbeddedFileProvider$instance extends IFileProvider$instance {}

export type EmbeddedFileProvider = EmbeddedFileProvider$instance & __EmbeddedFileProvider$views;


export interface ManifestEmbeddedFileProvider$instance {
    readonly Assembly: Assembly;
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(filter: string): IChangeToken;
}


export const ManifestEmbeddedFileProvider: {
    new(assembly: Assembly): ManifestEmbeddedFileProvider;
    new(assembly: Assembly, root: string): ManifestEmbeddedFileProvider;
    new(assembly: Assembly, root: string, lastModified: DateTimeOffset): ManifestEmbeddedFileProvider;
    new(assembly: Assembly, root: string, manifestName: string, lastModified: DateTimeOffset): ManifestEmbeddedFileProvider;
};


export interface __ManifestEmbeddedFileProvider$views {
    As_IFileProvider(): IFileProvider$instance;
}

export interface ManifestEmbeddedFileProvider$instance extends IFileProvider$instance {}

export type ManifestEmbeddedFileProvider = ManifestEmbeddedFileProvider$instance & __ManifestEmbeddedFileProvider$views;


export interface NotFoundDirectoryContents$instance {
    readonly Exists: boolean;
    GetEnumerator(): IEnumerator<IFileInfo>;
}


export const NotFoundDirectoryContents: {
    new(): NotFoundDirectoryContents;
    readonly Singleton: NotFoundDirectoryContents;
};


export interface __NotFoundDirectoryContents$views {
    As_IDirectoryContents(): IDirectoryContents$instance;
}

export interface NotFoundDirectoryContents$instance extends IDirectoryContents$instance {}

export type NotFoundDirectoryContents = NotFoundDirectoryContents$instance & __NotFoundDirectoryContents$views;


export interface NotFoundFileInfo$instance {
    readonly Exists: boolean;
    readonly IsDirectory: boolean;
    readonly LastModified: DateTimeOffset;
    readonly Length: long;
    readonly Name: string;
    readonly PhysicalPath: string;
    CreateReadStream(): Stream;
}


export const NotFoundFileInfo: {
    new(name: string): NotFoundFileInfo;
};


export interface __NotFoundFileInfo$views {
    As_IFileInfo(): IFileInfo$instance;
}

export interface NotFoundFileInfo$instance extends IFileInfo$instance {}

export type NotFoundFileInfo = NotFoundFileInfo$instance & __NotFoundFileInfo$views;


export interface NullChangeToken$instance {
    readonly ActiveChangeCallbacks: boolean;
    readonly HasChanged: boolean;
    RegisterChangeCallback(callback: Action<unknown>, state: unknown): IDisposable;
}


export const NullChangeToken: {
    new(): NullChangeToken;
    readonly Singleton: NullChangeToken;
};


export interface __NullChangeToken$views {
    As_IChangeToken(): Microsoft_Extensions_Primitives_Internal.IChangeToken$instance;
}

export interface NullChangeToken$instance extends Microsoft_Extensions_Primitives_Internal.IChangeToken$instance {}

export type NullChangeToken = NullChangeToken$instance & __NullChangeToken$views;


export interface NullFileProvider$instance {
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(filter: string): IChangeToken;
}


export const NullFileProvider: {
    new(): NullFileProvider;
};


export interface __NullFileProvider$views {
    As_IFileProvider(): IFileProvider$instance;
}

export interface NullFileProvider$instance extends IFileProvider$instance {}

export type NullFileProvider = NullFileProvider$instance & __NullFileProvider$views;


export abstract class PhysicalFileProvider$protected {
    protected Dispose(disposing: boolean): void;
}


export interface PhysicalFileProvider$instance extends PhysicalFileProvider$protected {
    readonly Root: string;
    UseActivePolling: boolean;
    UsePollingFileWatcher: boolean;
    Dispose(): void;
    GetDirectoryContents(subpath: string): IDirectoryContents;
    GetFileInfo(subpath: string): IFileInfo;
    Watch(filter: string): IChangeToken;
}


export const PhysicalFileProvider: {
    new(root: string): PhysicalFileProvider;
    new(root: string, filters: ExclusionFilters): PhysicalFileProvider;
};


export interface __PhysicalFileProvider$views {
    As_IFileProvider(): IFileProvider$instance;
}

export interface PhysicalFileProvider$instance extends IFileProvider$instance {}

export type PhysicalFileProvider = PhysicalFileProvider$instance & __PhysicalFileProvider$views;


