// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.FileSystemGlobbing.Internal
// Assembly: Microsoft.Extensions.FileSystemGlobbing

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { DirectoryInfoBase, FileInfoBase } from "../../Microsoft.Extensions.FileSystemGlobbing.Abstractions/internal/index.js";
import type { PatternMatchingResult } from "../../Microsoft.Extensions.FileSystemGlobbing/internal/index.js";
import type { IEnumerable_1, IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_2, Boolean as ClrBoolean, Object as ClrObject, String as ClrString, StringComparison, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface ILinearPattern$instance extends IPattern {
    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_ILinearPattern: never;

    readonly Segments: IList_1<IPathSegment>;
    CreatePatternContextForInclude(): IPatternContext;
}


export interface ILinearPattern$instance extends IPattern$instance {}

export type ILinearPattern = ILinearPattern$instance;

export interface IPathSegment$instance {
    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPathSegment: never;

    readonly CanProduceStem: boolean;
    Match(value: string): boolean;
}


export type IPathSegment = IPathSegment$instance;

export interface IPattern$instance {
    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPattern: never;

    CreatePatternContextForInclude(): IPatternContext;
}


export type IPattern = IPattern$instance;

export interface IPatternContext$instance {
    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IPatternContext: never;

    Declare(onDeclare: Action_2<IPathSegment, System_Internal.Boolean>): void;
    PopDirectory(): void;
    PushDirectory(directory: DirectoryInfoBase): void;
    Test(directory: DirectoryInfoBase): boolean;
    Test(file: FileInfoBase): PatternTestResult;
}


export type IPatternContext = IPatternContext$instance;

export interface IRaggedPattern$instance extends IPattern {
    readonly __tsonic_iface_Microsoft_Extensions_FileSystemGlobbing_Internal_IRaggedPattern: never;

    readonly Segments: IList_1<IPathSegment>;
    readonly StartsWith: IList_1<IPathSegment>;
    readonly Contains: IList_1<IList_1<IPathSegment>>;
    readonly EndsWith: IList_1<IPathSegment>;
    CreatePatternContextForInclude(): IPatternContext;
}


export interface IRaggedPattern$instance extends IPattern$instance {}

export type IRaggedPattern = IRaggedPattern$instance;

export interface PatternTestResult$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_PatternTestResult: never;

    readonly IsSuccessful: boolean;
    readonly Stem: string | null;
}


export const PatternTestResult: {
    new(): PatternTestResult;
    readonly Failed: PatternTestResult;
    Success(stem: string | null): PatternTestResult;
};


export type PatternTestResult = PatternTestResult$instance;

export interface MatcherContext$instance {
    readonly __tsonic_type_Microsoft_Extensions_FileSystemGlobbing_Internal_MatcherContext: never;

    Execute(): PatternMatchingResult;
}


export const MatcherContext: {
    new(includePatterns: IEnumerable_1<IPattern>, excludePatterns: IEnumerable_1<IPattern>, directoryInfo: DirectoryInfoBase, comparison: StringComparison): MatcherContext;
};


export type MatcherContext = MatcherContext$instance;

